### ISSUE TITLE
can cat cos and mba cos work together?

### ISSUE THREAD

**Issue by boz25** [intel/intel-cmt-cat#101]
I want to allocate both l3 cache and memory bandwidth to same core. but one core  seems to be associated with only one cos?

**Comment by kmabbasi** [comment]
Hi,

Yes one core is always associated with only one COS. However, you can allocate both L3 cache and memory bandwidth to same core by configuring the same COS for both L3 CAT and MBA.

Example to allocate cache and bandwidth for core 2:

- L3CAT COS 1=0xff
- MBA COS 1=50
- Core 2 = COS1 

Thanks,
Khawar

**Comment by boz25** [comment]
Thank you very much!

**Comment by kmabbasi** [comment]
We are glad to help you. 

I am going to close this issue now.

Thanks,
Khawar
