### ISSUE TITLE
Problems with setting COSs and associating with threads within an application

### ISSUE THREAD

**Issue by jdeters** [intel/intel-cmt-cat#102]
I'm currently trying to set up CAT within an application using the library and then later dynamically associating my COSs with particular threads. I'm using a Intel Xeon Gold 6148 which has an 11 way L3 cache.

I would like to create the following configuration:
- Associate each of my 11 ways in the L3 with exactly 1 of 11 COSs.
- Associate exactly one of my 11 COSs with exactly 1 of 11 threads.

It seems that if I do not start the library with the MSR interface, I cannot set up my COSs using the library. However, if I do not start the library using the OS interface, I cannot associate my threads to COSs. 

I have attempted to set the COSs with the MSR interface and then restart the library with the OS interface. This will allow me to associate _some_ of the COSs with threads, but the library seems to believe there is a limit of 8 COSs. 

Is the library inherently limited in functionality currently or am I misunderstanding how to use these two interfaces in conjunction?

**Comment by kmabbasi** [comment]
Hi Deter,
OS Interface takes common COSs used across allocation technology. In your case COS would be 8. So you have limitation of up-to use 8 CoSs when using OS interface.

For your use-case, the best option would be to use MSR interface. Using Taskset tool you can pin application/thread to specific core. After that you can associate each core to specific CoS using Pqos utility.

Please note that use of MSR interface and OS interface are not compatible. Therefore, we strongly recommend stick to one. Using MSR interface please ensure restctrl should not be mounted.

Thanks,
Khawar

**Comment by jdeters** [comment]
Thanks for the clarification. I will go that route.
