### ISSUE TITLE
Huge values for mbm readings

### ISSUE THREAD

**Issue by narru19** [intel/intel-cmt-cat#103]
Hi!

I'm currently integrating the library within a runtime, to monitor thread events. When polling data about memory bandwidth, I seem to obtain huge numbers at times. To serve as an example, I looked into pqos_mon_data internal structures and found these:

```
llc = 0,
mbm_local = 0,
mbm_total = 0,
mbm_remote = 0,
mbm_local_delta = 18446744073708863487,
mbm_total_delta = 18446744073708863487,
mbm_remote_delta = 0,
ipc_retired = 42679689609, 
ipc_retired_delta = 364573,
ipc_unhalted = 16749866215,
ipc_unhalted_delta = 726993,
ipc = 0.50148075703617501,
llc_misses = 150127261,
llc_misses_delta = 4976
```

It only seems to occur for memory bandwidth monitoring. More precisely I found this happening for delta values such as mbm_local_delta and mbm_remote_delta, never for readings.

Any idea what could be happening? These numbers seem to be similar throughout different executions, so I was thinking it could be due to an overflow...

- Platform: Intel(R) Xeon(R) CPU E5-2690 v4
- Library Version: Latest commit as of today (9cae4fce2229dd5339f7cb50c580f3af4e36dca4)
- Events monitored:
(PQOS_MON_EVENT_L3_OCCUP | PQOS_MON_EVENT_LMEM_BW | PQOS_MON_EVENT_RMEM_BW | PQOS_PERF_EVENT_LLC_MISS | PQOS_PERF_EVENT_IPC)

**Comment by kmabbasi** [comment]
Hi Toni,

Could you please provide more information such as OS and kernel version so that we can re-produce this issue?

Thanks,
Khawar

**Comment by narru19** [comment]
Hi Khawar,

Sure! My apologies for not including this beforehand:
OS: SUSE Linux Enterprise Server 12 SP2
Kernel: kernel-default-4.13.10-1.1

Regards,
Toni

**Comment by kmabbasi** [comment]
Hi Toni,

Could you please clarify that you are monitoring SW threads (pids) not the HW thread (cores)? 
Core monitoring using the OS interface will return incorrect values on this kernel (4.13) as monitoring per core is not supported in the kernel until 4.15+.

If you would like to monitor HW thread for kernel 4.13 you need to use MSR interface.

Thanks,
Khawar

**Comment by narru19** [comment]
Hi Khawar,

Correct, I am monitoring software threads through their thread ids (tids - pids).
As an example, to clarify, I am using the following interface in the library:
`configuration.interface = PQOS_INTER_OS;`
And when initializing threads, I do so with their thread id:
```
int ret = pqos_mon_start_pid(
	threadData->getTid(),
	eventList,
	NULL,
	threadData->getPQoSData()
);
```
Regards,
Toni

**Comment by kmabbasi** [comment]
Hi Toni,

Would you please check using pqos utility to monitor per pid/task monitoring whether you are getting the same results? 
e.g. pqos -I -p all:<pid>

Thanks,
Khawar

**Comment by narru19** [comment]
Hi Khawar,

I did try that before opening the issue. The binary seems to return correct values -- under 0.3 MB/s local memory BW, which is what I expected for the application I was running.

As for the values returned by the integration, I figured I might be collecting them wrongly, so I checked internal PQoS structures for threads and the values seemed to be wrong (overflowing).

Prior to this, a few months ago, everything seemed to work correctly. Recently, I updated the library I was using to intel-cmt-cat's latest commit, so I will try to downgrade the version again and test if I get huge magnitudes.

On top of this, I recently changed how the events were collected. I polled values as "double", but right now I'm using "size_t". Could this be an issue? (e.g., some counters returning negative values and thus showing up as overflow)

Meanwhile, I will try to downgrade and see if that fixes my problem :)

Thanks,
Toni

**Comment by narru19** [comment]
Hi Khawar,

I tested the previous version of intel-cmt-cat and I could not reproduce the huge readings. After that, I tested my integration with the latest version again and it seems to be working just fine right now.

My guess is that, since today I am the only user in the cluster, someone might have been using a profiling tool which used linux perf events as well. Would that conflict with the readings obtained?

You may close the issue for now, since I cannot reproduce these wrong readings again, so I guess the problem is in my end.

Thanks for the help!
Toni

**Comment by kmabbasi** [comment]
Thanks Toni for letting us know. 

I am going to close this issue now.

Regards,
Khawar

**Comment by narru19** [comment]
Hi,

I am reopening this issue as I have been able to reproduce and isolate this case. All the information about the processor model I am using and the version of the library that I specified above prevails.

I have found that, when reading values for events such as `mbm_local` or `mbm_remote`, some of the delta values seem to have overflown.

More specifically, when looking into the thread's data structures (`pqos_mon_data *`) with gdb, oftenly I see values as huge as the following:
```
(gdb) print data->values
$1 = {
  llc = 0,
  mbm_local = 0,
  mbm_total = 0,
  mbm_remote = 0,
  mbm_local_delta = 18446744073705709567,
  mbm_total_delta = 18446744073705652223,
  mbm_remote_delta = 0,
  ipc_retired = 7524081756,
  ipc_retired_delta = 575328,
  ipc_unhalted = 9638630110,
  ipc_unhalted_delta = 4594945,
  ipc = 0.12520889803904073,
  llc_misses = 28768088,
  llc_misses_delta = 20990
}
```
So what I have noticed is that:
* If I start monitoring a certain thread, then stop monitoring and collect delta values, readings for mbm may have overflown, but...
* If I start monitoring, then stop monitoring and compute the delta value myself using the stop-start values, the readings seem to be just fine.

Is it possible that these values are overflowing when computing their delta? Am I expected to cast these values to any specific signed type before using them?

Regards,
Toni

**Comment by kmabbasi** [comment]
Hi Toni,
We have investigated this issue and are able to reproduce it only on kernel version 4.13.x series except 4.13.0. It looks this is potentially be a kernel issue.

Could you please try either upgrade to kernel 4.14 or later (uses new resctrl interface) or downgrade to 4.13.0 or less (uses perf)?

Let's us know if it resolves your issue.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
Hi Toni,

I am going to close this issue now. If you have more question feel free to create new or reopen this issue.

Thanks,
Khawar

**Comment by narru19** [comment]
Hi Khawar,

I apologize for the delay!
I have tried it in kernel 4.15 and the issue does not seem to be there anymore, thanks!

Perhaps it would help someone else if a disclaimer was placed somewhere in the README about this issue (even though it is on the kernel side).

Thanks,
Toni
