### ISSUE TITLE
Issues in using pqos -I

### ISSUE THREAD

**Issue by alohamora** [intel/intel-cmt-cat#104]
I have recently installed intel-cmt-cat on my ubuntu 18.04 with kernel  version 4.15.0-46-generic.
I am not able to enable the resctrl kernel framework in my machine and there is no mount point for resctrl in /sys/fs.
On running pqos -I I get the following error
`NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: OS interface selected but not supported
ERROR: os_cap_init() error 8
`
Can anybody help me in setting up the framework. 
Thanks in advance

**Comment by kmabbasi** [comment]
Hi Aditya,

Could you please check output of 'cat /proc/filesystems' gives restctrl? If not, then you need to enable it into the kernel using https://github.com/intel/intel-cmt-cat/wiki#enabling-intelr-rdt-support-in-the-linux-kernel-os-interface

Thanks,
Khawar

**Comment by alohamora** [comment]
Hi @kmabbasi 
Thanks for the prompt reply.
On running cat /proc/filesystems, it does not five resctrl.
But the CONFIG_INTEL_RDT option mentioned in the link is already set in my config.

![Screenshot from 2019-04-09 18-39-25](https://user-images.githubusercontent.com/30872134/55802976-0b07e700-5af7-11e9-88f3-f74573465506.png)

**Comment by kmabbasi** [comment]
Can you please give us the details of following:

- what system you are using?
- output of 'pqos -V -s'

Thanks,
Khawar

**Comment by alohamora** [comment]
My system config is as follows:
CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Operating System: Ubuntu 18.04.2 LTS
Kernel: Linux 4.15.0-46-generic
Architecture: x86-64

output of pqos -V -s
![Screenshot from 2019-04-10 12-09-13](https://user-images.githubusercontent.com/30872134/55856955-7a2e1b80-5b89-11e9-8681-a3147a9ceb28.png)

**Comment by kmabbasi** [comment]
Hi Aditya,

Unfortunately Core i5 doesn't support RDT features. 

Please see following link for the HW that supports Intel(R) RDT 
https://github.com/intel/intel-cmt-cat/blob/master/README#L111

Meanwhile, I will proceed to close this issue.

If you need any further assistance, please do not hesitate to open new issue.

Thanks,
Khawar
