### ISSUE TITLE
using l3 cat feature on personal system

### ISSUE THREAD

**Issue by alohamora** [intel/intel-cmt-cat#105]
Hi @kmabbasi 
I read about the HW support for Intel(R) RDT but actually when I run `pqos -d` on my personal system, It lists L3 CAT as a Hardware capability, so shall I be able to use python pqos wrapper for my userspace program for cache allocation using the msr interface?

And One more thing, is there any addition to the supported hardware or is it limited to the ones listed in the README. 

The output of `pqos -d` is as follows:
![Screenshot from 2019-04-10 19-00-32](https://user-images.githubusercontent.com/30872134/55882915-f002a900-5bc2-11e9-8273-da8a42e2729a.png)
#104

**Comment by kmabbasi** [comment]
Hi Aditya,

In RDT we use different mechanisms to detect  RDT support on different platforms. One legacy mechanisms detects the presence of CAT MSRs and shows L3 capability detected if found. However, all features on new platforms are detected through CPUID.

The L3 CAT MSR may be present on your client platform therefore pqos utility detects L3 CAT support. However these MSRs are likely read only.

We test our RDT SW only on platforms which are listed in README. As best to our knowledge RDT support is not available on client platforms. 

Thanks,
Khawar

**Comment by PhilippWendler** [comment]
@kmabbasi Is the list in the README and the one in `lib/cap.c` really uptodate?

I have a Xeon E3-1230 v5, which is not listed there, but it is newer than a Xeon E3 v4, which is listed, so I guess it should also have that feature?

How can I test precisely whether CAT is supported on my system?

The output of `pqos -D` on this CPU is as follows:
```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: CPUID.0x7.0: Monitoring capability not supported!
WARN: Cache allocation not supported on model name 'Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz'!
ERROR: RDMSR failed for reg[0xc94] on lcore 0
Hardware capabilities
    Allocation
        Cache Allocation Technology (CAT)
            L3 CAT
                CDP: unsupported
                Num COS: 4
                Way size: 524288 bytes
                Ways contention bit-mask: 0x0
                Min CBM bits: 1
                Max CBM bits: 16
Cache information
    L3 Cache
        Num ways: 16
        Way size: 524288 bytes
        Num sets: 8192
        Line size: 64 bytes
        Total size: 8388608 bytes
    L2 Cache
        Num ways: 4
        Way size: 65536 bytes
        Num sets: 1024
        Line size: 64 bytes
        Total size: 262144 bytes
```

Does this mean that L3 CAT is not supported, because there is this warning? This warning comes from a hard-coded list in the source, which could be outdated, and below the warning the tool explicitly says that L3 CAT is supported. So I am confused now.

It would be great if you could tell me how to properly check for hardware support, thanks.

**Comment by kmabbasi** [comment]
Hi Philip,

Checking brand strings is a legacy detection mechanism that has only been validated on those specific models.
Feel free to add your CPU model to the list and validate that the utilities work as expected (see CAT usage examples in wiki). If so, you are welcome to submit a pull request to enable your platform.

Note: For Xeon CPU’s launched in 2016 onwards, feature enumeration is done through CPUID. If CPUID detection fails, then the features are not supported by your platform.

Thanks,
Khawar

**Comment by PhilippWendler** [comment]
@kmabbasi Thanks for the info.

As you see above, the tool says that CPUID detection fails:
```
WARN: CPUID.0x7.0: Monitoring capability not supported!
```

On the other hand, I looked in the wiki and tested one of the examples:
```
# pqos -e "llc:1=0x000f;llc:2=0x0ff0;"
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: CPUID.0x7.0: Monitoring capability not supported!
WARN: Cache allocation not supported on model name 'Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz'!
ERROR: RDMSR failed for reg[0xc94] on lcore 0
SOCKET 0 L3CA COS1 => MASK 0xf
SOCKET 0 L3CA COS2 => MASK 0xff0
Allocation configuration altered.
```

I guess this means that the feature is supported although both the hardcoded model list and the CPUID detection claim otherwise? I would be grateful if you could confirm this.

**Comment by kmabbasi** [comment]
Thanks Philipp for checking out CAT example.

Could you please provide the output of 'pqos -sV'?

Regards,
Khawar

**Comment by PhilippWendler** [comment]
Sure:
<details>
<summary>pqos/pqos -sV (after pqos -e "llc:1=0x000f;llc:2=0x0ff0;")</summary>

```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
INFO: CACHE: type 1, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 2, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 2, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 4 way(s), 1024 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 3, max id sharing this cache 16 (4 bits)
DEBUG: CACHE: inclusive, complex cache indexing, 16 way(s), 8192 set(s), line size 64, 1 partition(s)
DEBUG: Detected core 0, socket 0, L2 ID 0, L3 ID 0, APICID 0
DEBUG: Detected core 1, socket 0, L2 ID 1, L3 ID 0, APICID 2
DEBUG: Detected core 2, socket 0, L2 ID 2, L3 ID 0, APICID 4
DEBUG: Detected core 3, socket 0, L2 ID 3, L3 ID 0, APICID 6
DEBUG: Detected core 4, socket 0, L2 ID 0, L3 ID 0, APICID 1
DEBUG: Detected core 5, socket 0, L2 ID 1, L3 ID 0, APICID 3
DEBUG: Detected core 6, socket 0, L2 ID 2, L3 ID 0, APICID 5
DEBUG: Detected core 7, socket 0, L2 ID 3, L3 ID 0, APICID 7
WARN: CPUID.0x7.0: Monitoring capability not supported!
INFO: Monitoring capability not detected
INFO: CPUID.0x7.0: L3 CAT not detected. Checking brand string...
DEBUG: CPU brand string 'Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz'
WARN: Cache allocation not supported on model name 'Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz'!
ERROR: RDMSR failed for reg[0xc94] on lcore 0
INFO: L3CA capability detected
INFO: L3 CAT details: CDP support=0, CDP on=0, #COS=4, #ways=16, ways contention bit-mask 0x0
INFO: L3 CAT details: cache size 8388608 bytes, way size 524288 bytes
INFO: CPUID.0x7.0: L2 CAT not supported
INFO: L2CA capability not detected
INFO: CPUID.0x7.0: MBA not supported
INFO: MBA capability not detected
DEBUG: allocation init OK
DEBUG: monitoring init aborted: feature not present
L3CA COS definitions for Socket 0:
    L3CA COS0 => MASK 0xffff
    L3CA COS1 => MASK 0xf
    L3CA COS2 => MASK 0xff0
    L3CA COS3 => MASK 0xffff
Core information for socket 0:
    Core 0, L2ID 0, L3ID 0 => COS0
    Core 1, L2ID 1, L3ID 0 => COS0
    Core 2, L2ID 2, L3ID 0 => COS0
    Core 3, L2ID 3, L3ID 0 => COS0
    Core 4, L2ID 0, L3ID 0 => COS0
    Core 5, L2ID 1, L3ID 0 => COS0
    Core 6, L2ID 2, L3ID 0 => COS0
    Core 7, L2ID 3, L3ID 0 => COS0
```
</details>

**Comment by kmabbasi** [comment]
Thanks Philipp for providing the output.

Yes, your platform support CAT feature. Please submit a pull request to add support for this platform.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
I am going to close this issue now

If you have more question, please feel free to open new issue.

Thanks,
Khawar
