### ISSUE TITLE
initialization error

### ISSUE THREAD

**Issue by Young768** [intel/intel-cmt-cat#107]
Hi all, I tried to use your library to monitor memory bandwidth.
I installed your package using apt install intel-cmt-cat.

Then I test the pqos command, it shows these error. Does my hardware/software support this package?

root@user:~# pqos -r
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: Cache monitoring capability not supported!
WARN: Cache allocation not supported on model name 'Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz'!
ERROR: No Platform QoS capability discovered
ERROR: discover_capabilities() error 1
Error initializing PQoS library!

**Comment by mdcornu** [comment]
Hi,

Unfortunately your hardware does not support memory bandwidth monitoring.
Please see the [Hardware Support](https://github.com/intel/intel-cmt-cat/blob/master/README#L111) table in the README for CPU's supporting these features.

Regards,
Marcel

**Comment by Young768** [comment]
Oh Thanks for help. I will try on another server.
