### ISSUE TITLE
Unable to set COS for logical core

### ISSUE THREAD

**Issue by alohamora** [intel/intel-cmt-cat#110]
I am unable to set non-default COS for logical cores using pqos -a.
pqos -s output:
```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: CPUID.0x7.0: Monitoring capability not supported!
L3CA COS definitions for Socket 0:
    L3CA COS0 => MASK 0xffff
    L3CA COS1 => MASK 0xffff
    L3CA COS2 => MASK 0xffff
    L3CA COS3 => MASK 0xffff
Core information for socket 0:
    Core 0, L2ID 0, L3ID 0 => COS0
    Core 1, L2ID 1, L3ID 0 => COS0
    Core 2, L2ID 2, L3ID 0 => COS0
    Core 3, L2ID 3, L3ID 0 => COS0
    Core 4, L2ID 0, L3ID 0 => COS0
    Core 5, L2ID 1, L3ID 0 => COS0
    Core 6, L2ID 2, L3ID 0 => COS0
    Core 7, L2ID 3, L3ID 0 => COS0

```
![Screenshot from 2019-06-20 00-28-15](https://user-images.githubusercontent.com/30872134/59792979-0cbe0a00-92f3-11e9-9250-aba62d8f1933.png)

CPU version - Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz
interface - MSR

**Comment by kmabbasi** [comment]
are you able to change allocation of default COS (COS-0)? 

Thanks,
Khawar

**Comment by tkanteck** [comment]
Since it does not seem possible to write to PQR MSR on your system so I'd say CAT is not supported on it.

There will be some update to CAT enumeration procedure to address this problem since some new CPU's have COS and PQR MSR's that can be read but not written.

Thanks,
Tomasz

**Comment by alohamora** [comment]
> are you able to change allocation of default COS (COS-0)?
> 
> Thanks,
> Khawar

Yes I am able to change allocation for all the COS.
Output of `sudo pqos -e "llc:0=0x00ff;llc:1=0x000f;llc:2=0x0ff0;"`
```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: CPUID.0x7.0: Monitoring capability not supported!
SOCKET 0 L3CA COS0 => MASK 0xff
SOCKET 0 L3CA COS1 => MASK 0xf
SOCKET 0 L3CA COS2 => MASK 0xff0
Allocation configuration altered.
```

Output of `pqos -s` after that

```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: CPUID.0x7.0: Monitoring capability not supported!
L3CA COS definitions for Socket 0:
    L3CA COS0 => MASK 0xff
    L3CA COS1 => MASK 0xf
    L3CA COS2 => MASK 0xff0
    L3CA COS3 => MASK 0xffff
Core information for socket 0:
    Core 0, L2ID 0, L3ID 0 => COS0
    Core 1, L2ID 1, L3ID 0 => COS0
    Core 2, L2ID 2, L3ID 0 => COS0
    Core 3, L2ID 3, L3ID 0 => COS0
    Core 4, L2ID 0, L3ID 0 => COS0
    Core 5, L2ID 1, L3ID 0 => COS0
    Core 6, L2ID 2, L3ID 0 => COS0
    Core 7, L2ID 3, L3ID 0 => COS0

```

**Comment by alohamora** [comment]
> Since it does not seem possible to write to PQR MSR on your system so I'd say CAT is not supported on it.
> 
> There will be some update to CAT enumeration procedure to address this problem since some new CPU's have COS and PQR MSR's that can be read but not written.
> 
> Thanks,
> Tomasz

Actually I am able to write the default value i.e 0 to `PQOS_MSR_ASSOC` MSR
As you can see in the output of strace below, the error occurs when I am writing a value other than 0.
```
openat(AT_FDCWD, "/dev/cpu/0/msr", O_RDWR) = 4
pread64(4, "\0\0\0\0\0\0\0\0", 8, 3215) = 8
pwrite64(4, "\0\0\0\0\0\0\0\0", 8, 3215) = 8
fcntl(3, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_CUR, l_start=0, l_len=0}) = 0
fcntl(3, F_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_CUR, l_start=0, l_len=0}) = 0
pwrite64(4, "\377\0\0\0\0\0\0\0", 8, 3216) = 8
fcntl(3, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_CUR, l_start=0, l_len=0}) = 0
fcntl(3, F_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_CUR, l_start=0, l_len=0}) = 0
openat(AT_FDCWD, "/dev/cpu/1/msr", O_RDWR) = 5
pread64(5, "\0\0\0\0\0\0\0\0", 8, 3215) = 8
pwrite64(5, "\0\0\0\0\1\0\0\0", 8, 3215) = -1 EIO (Input/output error)

```

Thanks,
Aditya

**Comment by tkanteck** [comment]
Hi Aditya,

Thanks for checking it. Sorry but this is not due to some library problem. Simply, the hardware  doesn't allow for change of class of service association.

Thanks,
Tomasz

**Comment by kmabbasi** [comment]
Hi Aditya,

I am going to close this issue now. If you have more question feel free to either re-open this issue or create new one.

Thanks,
Khawar

**Comment by khushit-shah** [comment]
@tkanteck, @kmabbasi: But as per the manual at: 356688-intel-rdt-arch-spec.pdf, i5 11th gen should have B.1.4 L3 Cache Allocation Technology. But I am facing the same problem, setting the CLOS anything else than 0 given ERROR: WMSR ....
