### ISSUE TITLE
Does read/write to persistent memory count to mbt?

### ISSUE THREAD

**Issue by ccrhx4** [intel/intel-cmt-cat#111]
I have enabled the Optane DC Persistent Memory in a mix of memory mode and app direct mode. I am not sure if the memory bandwidth total includes the read/write to persistent memory. Please help me out. Thank you.

**Comment by kmabbasi** [comment]
Hi Hx,

Yes, persistent memory bandwidth should be counted in memory bandwidth total.

Thanks,
Khawar

**Comment by ccrhx4** [comment]
Hi Khawar,

Thank you for the clarification.

Hx
