### ISSUE TITLE
CAT and MBA wrong config and how to reinstall pqos

### ISSUE THREAD

**Issue by crbnb** [intel/intel-cmt-cat#115]
Hello!
(1) I use the command:
 ```
sudo pqos -e "llc:1=0x400"
```
However, sudo pqos -s shows:
```
    L3CA COS0 => MASK 0x7ff
    L3CA COS1 => MASK 0x600
    ...
    L3CA COS15 => MASK 0x7ff
   ...
```
(2) I use the command:
```
sudo pqos -e "mba:1=70"
```

However, sudo pqos -s shows:
```
 MBA COS1 => 90% available
```
And shows:
```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
SOCKET 0 MBA COS1 => 70% requested, 90% applied
Allocation configuration altered.
```
I set MBA level from 70 to 90, they all shown as follows:

```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
SOCKET 0 MBA COS1 => 70%(or 80% or 90%) requested, 90% applied
Allocation configuration altered.
```
However, set MBA level from 10 to 60, the config shows correctly.

(3) The number of CLOSs in MBA config is not equal to the core my server has. However,the guide of MBA shows that:

The MBA feature provides approximate and indirect per-core control over memory bandwidth.[here](https://software.intel.com/zh-cn/articles/introduction-to-memory-bandwidth-allocation)

(4) I reload this git code,and delete the old version,and  then use the command to install the new version:
```
sudo make

sudo gmake  
```

There is a feedback information:
```
 gmake[1]:Leaving directory `/home/nbjl/intel-cmt-cat/examples/c/PSEUDO_LOCK'
```
```
[nbjl@localhost intel-cmt-cat]$ sudo ./pseudo_lock
sudo: ./pseudo_lock: command not found
```
HOW CAN I SOLVE THESE PROBLEMS ABOVE ???

I need pqos to collect the experimental data urgently. Could you give me a reply as soon as possible?
Thank you very much!
Thanks!

**Comment by kmabbasi** [comment]
Hi,

1. Certain bits of the CBM (cache ways) may be used by other entities in the platform (e.g. an integrated graphics engine or hardware units outside the processor core and have direct access to L3). Please refer to Intel SDM vol 3b Chapter 17 (Figure 17-32).

2. Please refer section 3.4 in the following document for information:
https://software.intel.com/en-us/intel-resource-director-technology-rdt-reference-manual

3.  There is no correlation between COS and number of cores.

4. Please use make and not gmake to build the software (as non-root user). [Refer to this link for installation.](https://github.com/intel/intel-cmt-cat/blob/1cac0083b05848bf3a0f66e087f35226b1aa0930/INSTALL#L38)

Thanks,
Khawar

**Comment by crbnb** [comment]
Thank you for your quick reply! We have the problem as following:

1. It's confused that we can use the bits of the CBM 0x400 and we use MBA to allocate bandwidth from 10% to 100% with 10% per step for a long time. It seems that it not work suddenly. Now I reinstall pqos and msr-tools successfully cause we find the phenomenon shown in 2 by revising the source code of pqos code.

2. We do meet the problem values greater than 10 (decimal) and less than 40 (decimal) written to the MBA delay value (Bits [15:0]) mightbe read back as 10 (decimal). How can we solve it?

**Comment by kmabbasi** [comment]
1. The CBM bits used by other entities are described as a "contention bit-mask" the pqos logs.
Example: 
```
$ pqos -sv
...
INFO: L3 CAT details: CDP support=1, CDP on=0, #COS=16, #ways=11, ways contention bit-mask 0x600
...
```
Setting one of these bits will always result in both bits being set. If you require to set a single way for a specified CLOS, you will have to use bits outside the contention bit-mask.


2. This is a HW related issue on Intel® Xeon® Scalable Processors, as mentioned in the reference guide, unfortunately no SW workaround is available.

**Comment by kmabbasi** [comment]
Hi,

Going to close this issue now.  If you have more question, feel free to open new issue.

Thanks,
Khawar
