### ISSUE TITLE
Clarification for llc_misses and ipc field in pqos_event_values

### ISSUE THREAD

**Issue by alohamora** [intel/intel-cmt-cat#118]
Hi,

I need some clarification regarding the `llc_misses` and `ipc` field in `pqos_event_values` struct.

I am monitoring data per core using `pqos_mon_poll` and would like to know what does `llc_misses` field denote, does it show the total no of llc misses from the start of monitoring or it has some other meaning?
And similary does the `ipc` field denote the average no of instructions retired / cycle during the monitoring period?

Regards,
Aditya

**Comment by mdcornu** [comment]
Hi Aditya,

These values represent LLC misses, instructions retired / cycles (average IPC) since the last call to `pqos_mon_poll`.

Regards,
Marcel

**Comment by alohamora** [comment]
Thanks for the clarification @mdcornu
