### ISSUE TITLE
Support for resetting monitoring for select cores

### ISSUE THREAD

**Issue by alohamora** [intel/intel-cmt-cat#119]
Hi,

Currently the function `pqos_mon_reset` only allows to reset the monitoring for all the cores in the system. Therefore it is not possible to reset RMID for a subset of cores in the system.
So it would be great if `pqos_mon_reset` takes an input argument as a list of cores so that we can reset monitoring for a select subset of cores.
This feature can be useful when two instances of monitoring are running for two disjoint sets of cores and we would like to reset monitoring for one of the instances.

Regards,
Aditya

**Comment by mdcornu** [comment]
Hi Aditya,

When 2 instances are monitoring 2 disjoint sets of cores, simply stopping monitoring 1 of the instances (with `pqos_mon_stop`) will reset the RMID back to default, effectively resetting those cores.

Regards,
Marcel

**Comment by alohamora** [comment]
Hi @mdcornu.

Thanks for clearing that out.

Regards,
Aditya
