### ISSUE TITLE
The following problem occurs with rdtset

### ISSUE THREAD

**Issue by wsm6636** [intel/intel-cmt-cat#121]
Incorrect invocation!

no matter what I type

**Comment by mdcornu** [comment]
Did you try paste examples from the README?

Example: `sudo rdtset  -t 'l3=0xf;cpu=1' -c 1 -k id`

Regards,
Marcel

**Comment by kmabbasi** [comment]
Hi,

It's been more than 3 weeks no response from your side. Looks like it resolves your issue. I am going to close this issue now. 

Thanks,
Khawar

**Comment by gureya** [comment]
Hi,

Has this issue been resolved, I'm also getting a similar error i.e., Incorrect invocation! when running the example already provided in the documentation: sudo rdtset -t 'mba=20;cpu=3' –c 3 intel-cmt-cat/tools/membw/membw –c 3 –b 10000 –read

**Comment by kmabbasi** [comment]
We tried this command ourselves and found that Linux shell doesn't translate special characters properly. Therefore, you need to type either full command or at least special characters yourself. Also membw operation parameter should have like this --read instead -read 

Could you please try again and let us know which documentation you got this command? 

Thanks,
Khawar

**Comment by gureya** [comment]
Yes, you are right. I typed the full command and it works!

Thanks!

**Comment by kmabbasi** [comment]
We are glad it works for you. For now I am going to close this issue.

Thanks,
Khawar
