### ISSUE TITLE
How to disable L3

### ISSUE THREAD

**Issue by skia92** [intel/intel-cmt-cat#124]
Hi,

Can I disable L3 by using `pqos`? (i.e. `pqos -e "llc:0=0x0"`)
I found that the command above is not currently possible due to the below snippet
https://github.com/intel/intel-cmt-cat/blob/f8d4d5df480838b538dc89dac75f516e99577f18/pqos/alloc.c#L181-L184

But I also found the possible case and reference from #78 and [stackoverflow](https://stackoverflow.com/questions/48360238/how-can-the-l1-l2-l3-cpu-caches-be-turned-off-on-modern-x86-amd64-chips#comment83717720_48361539) (The comment is referring to the intel SDM and I was trying to find the point she referred but I haven't gotten anything about "not chunks at all")

**Comment by kmabbasi** [comment]
CAT cannot be used to disable cache. Minimum 1 cache way is required.

Thanks,
Khawar

**Comment by skia92** [comment]
Ah,  thanks.
