### ISSUE TITLE
 Intel(R) RDT hardware support have any update?

### ISSUE THREAD

**Issue by whytehuang** [intel/intel-cmt-cat#126]
Dear developers, does now Hardware Support have Purley refresh and Whitley?
I try Purley refresh platform can work, but still have same problem with 
#69(65% - 94% mba cos value generates the same result 90%)
and I check read me not show  Purley refresh or Whitley, so can update hardware support on READ ME?

Configuration
ubuntu18.04.3(Hareware kernel 5.0)
intel-cmt-cat” (Version 3.1) 

Thanks and best regards,
Whyte

**Comment by kmabbasi** [comment]
Hi Whyte,

Thanks for your feedback. 

RDT support is available up to Purley refresh platform.

We have put in our backlog to update README for Purley refresh support. Alternatively, feel free to submit patch.

The link of Purley errata is https://software.intel.com/en-us/intel-resource-director-technology-rdt-reference-manual

You can always find more details in our "Wiki>Useful Links".

Thanks,
Khawar

**Comment by whytehuang** [comment]
Dear Khawar
Thanks, so can I close this when README  update?

Thanks,
Whyte

**Comment by kmabbasi** [comment]
Hi Whyte,

Just to let you know that the README has been updated!

Thanks,
Khawar

**Comment by whytehuang** [comment]
Hi Khawar 
I can see README have update Purley refresh platform, thanks~
So how about Intel Whitley platform? can support in version 3.1?

**Comment by kmabbasi** [comment]
These are architectural features and should work on all platforms supporting these technologies.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
Hi Whyte,

README of supporting hardware has already been updated. Therefore, by now I am going to close this issue.

Thanks,
Khawar
