### ISSUE TITLE
pqos: error while loading shared libraries: libpqos.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jakechasan** [intel/intel-cmt-cat#127]
I am trying to configure the `intel-cmt-cat` package but running into an issue. I have done the installation as specified in the readme, but am getting the following error when I try to run pqos or any of the other sample programs included within the project:

> pqos: error while loading shared libraries: libpqos.so.3: cannot open shared object file: No such file or directory

I have verified the the file `libpqos.so.3` does indeed exist, and have seen that the readme suggests:

> Note: It may be necessary to set "LD_LIBRARY_PATH=path/to/libpqos.so" when running the utility with local shared library.

I am not too sure where to include this as I have searched through the project and cannot find another reference to `LD_LIBRARY_PATH`.

Has anyone else experienced this error?

The system I am running on has the following processor:

> **Processor Information**
> Name                          Intel Xeon E5-2620 v4
> Topology                    1 Processor, 8 Cores, 16 Threads
> Identifier                    GenuineIntel Family 6 Model 79

**Comment by mdcornu** [comment]
Hi Jake,

Please see our FAQ page on the wiki [here](https://github.com/intel/intel-cmt-cat/wiki/FAQ#when-i-try-to-run-the-utility-i-get-the-following-error-message). Hopefully this solution works for you.

You shouldn't need to use set LD_LIBRARY_PATH when the library is installed, but if the above solution doesn't work (assuming the library is installed in /usr/local/lib), you could try the command:
`sudo LD_LIBRARY_PATH=/usr/local/lib pqos -s`

Or simply export the env variable and run the pqos utility:
`export LD_LIBRARY_PATH=/usr/local/lib`
`sudo pqos -s`

Regards,
Marcel

**Comment by jakechasan** [comment]
Thank you for your reply.

After entering `sudo LD_LIBRARY_PATH=/usr/local/lib pqos -s`, I get the following output:

> NOTE:  Mixed use of MSR and kernel interfaces to manage
>        CAT or CMT & MBM may lead to unexpected behavior.
> L3CA COS definitions for Socket 0:
>     L3CA COS0 => MASK 0xfffff
>     L3CA COS1 => MASK 0xfffff
>     L3CA COS2 => MASK 0xfffff
>     L3CA COS3 => MASK 0xfffff
>     L3CA COS4 => MASK 0xfffff
>     L3CA COS5 => MASK 0xfffff
>     L3CA COS6 => MASK 0xfffff
>     L3CA COS7 => MASK 0xfffff
>     L3CA COS8 => MASK 0xfffff
>     L3CA COS9 => MASK 0xfffff
>     L3CA COS10 => MASK 0xfffff
>     L3CA COS11 => MASK 0xfffff
>     L3CA COS12 => MASK 0xfffff
>     L3CA COS13 => MASK 0xfffff
>     L3CA COS14 => MASK 0xfffff
>     L3CA COS15 => MASK 0xfffff
> Core information for socket 0:
>     Core 0, L2ID 0, L3ID 0 => COS0, RMID0
>     Core 1, L2ID 1, L3ID 0 => COS0, RMID0
>     Core 2, L2ID 2, L3ID 0 => COS0, RMID0
>     Core 3, L2ID 3, L3ID 0 => COS0, RMID0
>     Core 4, L2ID 4, L3ID 0 => COS0, RMID0
>     Core 5, L2ID 5, L3ID 0 => COS0, RMID0
>     Core 6, L2ID 6, L3ID 0 => COS0, RMID0
>     Core 7, L2ID 7, L3ID 0 => COS0, RMID0
>     Core 8, L2ID 0, L3ID 0 => COS0, RMID0
>     Core 9, L2ID 1, L3ID 0 => COS0, RMID0
>     Core 10, L2ID 2, L3ID 0 => COS0, RMID0
>     Core 11, L2ID 3, L3ID 0 => COS0, RMID0
>     Core 12, L2ID 4, L3ID 0 => COS0, RMID0
>     Core 13, L2ID 5, L3ID 0 => COS0, RMID0
>     Core 14, L2ID 6, L3ID 0 => COS0, RMID0
>     Core 15, L2ID 7, L3ID 0 => COS0, RMID0

Then, when I try to run `pqos -h`, I get the same error:
> pqos: error while loading shared libraries: libpqos.so.3: cannot open shared object file: No such file or directory

The contents of `/usr/local/lib` are as follows:
> libpapi.a     libpapi.so.5.5.1    libpfm.so        libpqos.so        pkgconfig
> libpapi.so    libpapi.so.5.5.1.0  libpfm.so.4      libpqos.so.3
> libpapi.so.5  libpfm.a            libpfm.so.4.8.0  libpqos.so.3.1.0

Am I missing something about the contents of the library folder? Thank you again for the help.

**Comment by jakechasan** [comment]
So I was able to solve the issue by running `sudo` before the command
