### ISSUE TITLE
CAT and DDIO

### ISSUE THREAD

**Issue by mpurzynski** [intel/intel-cmt-cat#128]
Hey, while tuning a network inspection application I stumbled upon the CAT technology and it looks like it could help with cache trashing.

I'm tuning servers with 2x Xeon(R) Gold 6126, one X710 per NUMA node, all memory channels filled. Cores isolated - core 0 and 13 (so first on each package) left for OS.

INFO: L3 CAT details: CDP support=1, CDP on=0, #COS=16, #ways=11, ways contention bit-mask 0x600

Cores 1 and 14 (second on each package) - dedicated for IRQ plus SoftIRQ/NAPI. Nothing else runs there.

Application runs with multiple threads, one thread per core, pinned.

**What I'm trying to achieve:**
1. preserve the precious data from DDIO so that my app can consume packets from L3 (making L3 efficiently a transmission bus)
2. isolate OS from packet reception, DDIO, all application threads

**Questions**
1. does "ways contention bit-mask 0x600" (two MSB) mean DDIO will write into those ways and those ways only? Does DDIO respect CAT?
2. how do I increase the number of cache ways DDIO can write into?
3. what do you think about my crazy ideas here?
4. In order to make sure CAT is respected by the core doing kernel-side network proessing, I set the monitoring interface down, setup CAT, brought interface up, configured IRQ affinity.
Any better way to make sure core's 1 LLC usage won't "spill? What if I hot-un-plugged that core, configured CAT, plugged it back?

**I configured CAT like follows**

COS 2 - 1 cache way - for OS to trash
pqos -e "llc:2=0x1"
pqos -a "llc:2=0"
pqos -a "llc:2=12"
COS 3 - 2 cache ways - exclusive of COS 2 and COS 4 - for IRQ, not shared
pqos -e "llc:3=0x180"
pqos -a "llc:3=1"
pqos -a "llc:3=13"
COS 2 6 cache ways - for Suricata, not shared
pqos -e "llc:4=0x7e"
pqos -a "llc:4=2"
pqos -a "llc:4=3"
pqos -a "llc:4=4"
pqos -a "llc:4=5"
pqos -a "llc:4=6"
pqos -a "llc:4=7"
pqos -a "llc:4=8"
pqos -a "llc:4=9"
pqos -a "llc:4=10"
pqos -a "llc:4=11"
pqos -a "llc:4=14"
pqos -a "llc:4=15"
pqos -a "llc:4=16"
pqos -a "llc:4=17"
pqos -a "llc:4=18"
pqos -a "llc:4=19"
pqos -a "llc:4=20"
pqos -a "llc:4=21"
pqos -a "llc:4=22"
pqos -a "llc:4=23"

**Comment by tkanteck** [comment]
Hello Michal,

Thanks for looking deeper into Intel(R) RDT.

Some answers to your questions:

1) Yes, DDIO would be included in the contention mask

2) Sorry but RDT/CAT are not equipped to modify DDIO mask

3) I don't find them crazy at all :) In my opinion, this is exactly what one should do to optimize an application with use of Intel(R) RDT at system level.
For some applications resource allocation changes will make an impact for others not. It depends if application's performance is constrained by a resource like LLC or memory bandwidth.
Please check performance counters of your application (cache miss vs hits etc., memory bandwidth) to understand the bottle neck a bit better.
One simple way of checking if application is LLC constrained is to limit its LLC access to the minimum and observe change in performance vs bigger access masks (please use longer time span for the observation or flush cache between LLC configuration changes).
Some interesting DDIO/PCIe device related counters are also described here:
https://www.intel.com/content/www/us/en/processors/xeon/scalable/xeon-scalable-uncore-performance-monitoring-manual.html

4) I assume that kernel resource control file system / OS interface is used here, is it correct?
Please note that pqos supports number ranges, so a simpler one line notation can be used i.e. 'pqos -a "llc:4=2-11,14-23"'
I think there is no need to turn off monitoring as monitoring and allocation are two independent technologies.
Class assignment should be restored when core comes back online again, after being offline.

At first glance it looks good and it should do what you described at the beginning.
Did this LLC partitioning improve performance or latency of the application?

Looking forward to hearing from you.

Thanks,
Tomasz

**Comment by kmabbasi** [comment]
It's been more than 3 weeks we haven't heard anything back. 

Considering this issue has been resolved therefore closing now.

Thanks,
Khawar
