### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by psaigal95** [intel/intel-cmt-cat#131]
[root@server ~]# pqos -V -s
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
**Segmentation fault (core dumped)**

[root@server ~]# pqos -V -s
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Segmentation fault (core dumped)
[root@beast4 ~]# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              18
On-line CPU(s) list: 0-17
Thread(s) per core:  1
Core(s) per socket:  18
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz
Stepping:            4
CPU MHz:             4800.000
CPU max MHz:         4800.0000
CPU min MHz:         1200.0000
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0-17
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d

I just quickly wanted to confirm if this is a hardware problem?
The reason I am asking this because I have seen different error message when the problem is due to  the hardware on different machines.

**Comment by kmabbasi** [comment]
Hi,

It shouldn't throw segmentation fault error regardless what platform is.

Could you please provide more information such as what OS and kernel you are using, where did you get pqos i.e Fedora, Ubuntu or GitHub?

If you haven't build it from GitHub. It may be useful to use GitHub version since we do regular updates on GitHub.

Thanks,
Khawar

**Comment by psaigal95** [comment]
Hi Khawar,
It seems like reinstalling it fixed this issue. Thanks for your help.

Thanks,
Prateek

**Comment by tkanteck** [comment]
Hi @psaigal95,
Thanks for letting us know.
Out of curiosity, could you share with us outputs of "pqos -s -V" and "pqos -d" from the i9 system?
We have never tried our tools on any of these.
Thanks,
Tomasz

**Comment by psaigal95** [comment]
Hi Tomasz,

There you go:
[pqos-d.txt](https://github.com/intel/intel-cmt-cat/files/3849825/pqos-d.txt)
[pqos-s-V.txt](https://github.com/intel/intel-cmt-cat/files/3849826/pqos-s-V.txt)

These outputs looks okay to you, right?

Thanks,
Prateek

**Comment by tkanteck** [comment]
Thanks Prateek! Yes, they look OK and interesting. When it comes to available RDT features it looks similar to Intel(R) Xeon(R) SP parts.
Cheers,
Tomasz
