### ISSUE TITLE
Can Cat be managed through the OS interface now?

### ISSUE THREAD

**Issue by chenhy97** [intel/intel-cmt-cat#132]
I want to dynamically change the llc size for my application at runtime. From FAQ, I know that the old version of intel-cmt-cat only allows the users to manage CAT through MSR interface. Therefore, users cannot change llc per process. I want to know whether CAT could be managed through the OS interface in the lastest version.  
If not, resctrl is an option, right?

**Comment by tkanteck** [comment]
Hi @chenhy97 
Yes, this is supported (depends on kernel version & toll version).
Please see: https://github.com/intel/intel-cmt-cat/wiki/Usage-Examples#14-using-the-oskernel-interface-v10

**Comment by chenhy97** [comment]
@tkanteck  thanks your answer!
