### ISSUE TITLE
How to validate the CAT operation?

### ISSUE THREAD

**Issue by chenhy97** [intel/intel-cmt-cat#134]
I used docker to deploy mongo on a server and used a workload generator(YCSB) to generate workloads to mongo. 
Some important information of the server: ways=11 and way size = 1572864 bytes
When YCSB begins to generate workload to mongo, I use the rdtset tool to set  mongo-docker process's  llc mask to 0x001. While the mongo-docker process is running, I also use [pqos -I -p all:$mongo-docker-PID] to monitor the change of its llc. 
In my opinion, after I set its llc mask to 0x001, the LLC[KB] will drop to less than 1536 which is the size of one way. However, it didn't.
I want to know why and how can I validate the CAT operation.

**Comment by kmabbasi** [comment]
Hi,
LLC occupancy may not drop until the cache lines already installed in LLC have been evicted.
To force this, you can run a noisy neighbour application in parallel (associated to a different COS) that will evict workload data remaining in LLC.
Or, flush the cache using instructions such as CLFLUSH or WBINVD.

You should then see the expected LLC occupancy drop

Thanks,
Khawar

**Comment by chenhy97** [comment]
Thank you!
