### ISSUE TITLE
Config persisting

### ISSUE THREAD

**Issue by krunal1313** [intel/intel-cmt-cat#136]
Hello,

I've observed that masks and associations gets reset to default after system reboot.

Is there any way to persist those changes?
I've a production server which is rebooted every weekend and I dont want to set the config each time after reboot.

Thanks

**Comment by kmabbasi** [comment]
Hi Krunal,

Yes, pqos tool allows to import configurations from config file (pqos -f). Once you define configurations to config file then there are different ways in Linux you can load script during bootup phase.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
As we didn't hear back from you, therefore we consider this issue has been resolved.
