### ISSUE TITLE
How to configure COS to the cores of specific socket.

### ISSUE THREAD

**Issue by kakaiu** [intel/intel-cmt-cat#137]
Hi,

In the usage example, it separately shows assigning a COS to sockets and assigning a COS to cores.
But it is confusing that how to assign a COS to some cores of a specific socket?

What is the relationship between core id and socket id in the usage example? For example, is it like that core 0 and core 1 are of socket 0 and core 2 and core 3 are of socket 1, representing 4 cores on 2 sockets? or core 0-3 are of socket 0 and socket 1, representing 4+4=8 cores on 2 sockets?

Thanks,
Zhe

**Comment by kmabbasi** [comment]
Hi Zhe,

By default pqos configures COS across all sockets. However, it is possible to configure COS of specific socket using '@' operator, like mentioned in the usage example

https://github.com/intel/intel-cmt-cat/wiki/Usage-Examples#set-cos-1-on-all-sockets-cos-2-on-socket-0-and-1-and-cos-3-on-sockets-2-to-3

Thanks,
Khawar

**Comment by kmabbasi** [comment]
Hi Ahe,

We haven't heard anything back from you. We are considering this issue has been resolve. Therefore, closing it now.

Thanks,
Khawar
