### ISSUE TITLE
Potential issue during MBA reset on AMD

### ISSUE THREAD

**Issue by mdcornu** [intel/intel-cmt-cat#139]
MBA COS get reset to 0 by default.
This may not be correct behavior on AMD platforms.

https://github.com/intel/intel-cmt-cat/blob/1e6ee29be038ca67cf8fe9760bf53d97dde849e3/lib/allocation.c#L1642

**Comment by babumoger** [comment]
Ok. Sure.  Will investigate.

**Comment by babumoger** [comment]
Marcel, 
Yes. When I reset the MBA values(pqos -R), I see the MBA values are getting reset to 0. I expected it to go back to default values. Shouldn't we reset it to default maximum value(100 for Intel and 0x800 for AMD)?  I am thinking this may be generic issue.

**Comment by tkanteck** [comment]
It doesn't seem to be a generic issue as the MBA reset works fine on Intel platforms

**Comment by babumoger** [comment]
Ok. got it. The reset values for Intel and AMD are different.  For Intel, the reset value is 0 and for AMD reset value is 0x800.
This patch should fix it.  Will sent a pull request.

diff --git a/lib/allocation.c b/lib/allocation.c
index d850c39..37b20f3 100644
--- a/lib/allocation.c
+++ b/lib/allocation.c
@@ -1632,6 +1632,8 @@ hw_alloc_reset(const enum pqos_cdp_config l3_cdp_cfg,
                  */
                 for (j = 0; j < mba_id_num; j++) {
                         unsigned core = 0;
+                        unsigned val = (m_cpu->vendor == PQOS_VENDOR_AMD)
+                                        ? PQOS_MBA_MAX_AMD : 0;

                         ret = pqos_cpu_get_one_by_mba_id(m_cpu, mba_ids[j],
                                                          &core);
@@ -1639,7 +1641,7 @@ hw_alloc_reset(const enum pqos_cdp_config l3_cdp_cfg,
                                 goto pqos_alloc_reset_exit;

                         ret = alloc_cos_reset(vconfig->mba_msr_reg,
-                                              mba_cap->num_classes, core, 0);
+                                              mba_cap->num_classes, core, val);
                         if (ret != PQOS_RETVAL_OK)
                                 goto pqos_alloc_reset_exit;
                 }

**Comment by kmabbasi** [comment]
Thanks Babu

Patch has been merged to master branch. Therefore, closing this issue now.

Thanks,
Khawar
