### ISSUE TITLE
Question about MBA and LLC CLOS

### ISSUE THREAD

**Issue by Pl4tiNuM** [intel/intel-cmt-cat#140]
Hello,

I have a question regarding the Classes of Service (CLOS) for Memory Bandwidth Allocation and Last Level Cache Allocation. I am currently using a dual socketed Intel® Xeon® Gold 6138 CPU.

The question is whether the CLOS for MBA and CLOS L3CA are the same. For example if I set the following mask for L3CA CLOS1:

`pqos -e "llc:1=0x000f`

and also set MBA to 30% for CLOS1 like:

`pqos -e "mba:1=30"`

then if I map core 0 to CLOS 1 like

`pqos -a "llc:1=0"`

will core 0 get 4 cache ways and 30% memory bandwidth? 

- If yes, why are there 16 L3CA CLOS and only 8 MBA CLOS on my system?

- If not, how can I assign different MBA and L3CA CLOS? If I do the following:

`pqos -e "mba:1=30"`
`pqos -e "llc:2=0x000f"`
`pqos -a 'core:1=0'`
`pqos -a "llc:2=0"`

Then the CLOS for core 0 results to CLOS2
`
...
Core information for socket 0:
    Core 0, L2ID 0, L3ID 0 => COS2, RMID0
...
`
I am not sure If my question is clear, but I can clarify any further missunderstandings. I have also read most of the other issues, but I could not find any similar question.

Thanks in advance for your help,
Dimos

**Comment by kmabbasi** [comment]
Hi Dimos,

Yes, you are right! In your scenario core 0 will get 4 cache ways and 30% memory bandwidth.

Number of CLOS vary per feature/platform. 
Just to note that on your platform, as MBA has 8 CLOS and L3 CAT has 16 so first 8 CLOS can be used together for MBA and CAT. However, latter 8 are only for L3CAT, and will have 100% bandwidth available.

Thanks,
Khawar

**Comment by Pl4tiNuM** [comment]
Thanks a lot for the reply and the help!
