### ISSUE TITLE
Dynamic PID Monitoring

### ISSUE THREAD

**Issue by melkoncha** [intel/intel-cmt-cat#142]
Hello everyone,

As title says, I would like to know if there's a possibility to dynamically start PID monitoring. I am using _pqos -I -p  all:<>_, with passing 10 PIDs to monitor. I was wondering if I can dynamically add another PID to monitor, or even replace one of the 10 PIDs I originally passed as arguments. I tried to use **pqos_mon_start_pids()** with a new PID but nothing seems to happen. Thank you in advance.

Regards,
Melkon

**Comment by kmabbasi** [comment]
Hi Melkon,

You can try these APIs 

- for adding pids https://github.com/intel/intel-cmt-cat/blob/master/lib/pqos.h#L583

- for removing pids https://github.com/intel/intel-cmt-cat/blob/master/lib/pqos.h#L597

Thanks,
Khawar

**Comment by melkoncha** [comment]
Hello Khawar,

Thank you for the fast reply and your useful information. I am going to close this issue now.

Regards,
Melkon
