### ISSUE TITLE
No Os capabilities Need Help 

### ISSUE THREAD

**Issue by Tobiaswei** [intel/intel-cmt-cat#143]
root@super27:/boot# pqos -d
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: resctl filesystem mounted! Using MSR interface may corrupt resctrl filesystem and cause unexpected behaviour
Hardware capabilities
    Monitoring
        Cache Monitoring Technology (CMT) events:
            LLC Occupancy (LLC)
        Memory Bandwidth Monitoring (MBM) events:
            Total Memory Bandwidth (TMEM)
            Local Memory Bandwidth (LMEM)
            Remote Memory Bandwidth (RMEM) (calculated)
        PMU events:
            Instructions/Clock (IPC)
            LLC misses
    Allocation
        Cache Allocation Technology (CAT)
            L3 CAT
                CDP: disabled
                Num COS: 16
        Memory Bandwidth Allocation (MBA)
            Num COS: 8

root@super27:/boot# pqos -I -p
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Monitoring top-pids enabled
ERROR: Failed to open perf event!
ERROR: Failed to start perf counters for Unhalted CPU Cycles
ERROR: Failed to start all selected OS monitoring events
PID 13475 monitoring start error,status 1

root@super27:/boot# cat /lib/modules/$(uname -r)/build/.config | grep -i CONFIG_INTEL_RDT
CONFIG_INTEL_RDT=y

root@super27:/boot# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-4.15.0-70-generic root=/dev/mapper/VG_00-root ro rdt=cmt,mbmtotal,mbmlocal,l3cat,l3cdp,mba text nouveau.modeset=0

**Comment by kmabbasi** [comment]
Hi Tobiaswei,

Just to ensure that you are using RDT on host NOT on guest (VM, container, etc…). If you are using host could you please provide us following information:

1. What operating system are you using?
2. output of 'cat /proc/cpuinfo' to know the HW
3. check that 'sudo pqos' working fine
4. Output of 'sudo pqos -I -sV'
5. Try to monitor with known pid 'sudo pqos -I -p all: < pid >

Thanks,
Khawar

**Comment by kmabbasi** [comment]
Hi,

We haven't heard anything back from you. Therefore, we are considering it is resolved and closing now.

Thanks,
Khawar

**Comment by Chinmay-Gupta** [comment]
Hi,
I want to clear off one thing - does RDT not work with VMs ? If MSR doesn't work in that case, can resctrl OS implementation still work?

Thanks,
Chinmay
