### ISSUE TITLE
Recompilation of applications required for next intel-cmt-cat release

### ISSUE THREAD

**Issue by kmabbasi** [intel/intel-cmt-cat#144]
The next intel-cmt-cat release version will be 4.0.  

This next release will require recompilation of applications **due to internal changes in the library.
No other application changes should be necessary.**

**Comment by ColinIanKing** [comment]
Thanks for the info; any idea of the timescale for the 4.0 release?

**Comment by kmabbasi** [comment]
Hi Colin,

We are expecting our next release in June.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
closing it as 4.0 has been released!
