### ISSUE TITLE
Memory - illegal accesses in function resctrl_mon_parse

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-cmt-cat#148]
Hi,

Static analsis on intel-cmt-cat found a potential memory access issue in resctrl_mon_parse(), the analysis is as follows:

*** CID 210449:  Memory - illegal accesses  (BUFFER_SIZE_WARNING)
/lib/resctrl_monitoring.c: 969 in resctrl_mon_parse()

963                             if (grp == NULL) {
964                                     if (grps_num + 1 == grps_size) {
965                                             ret = PQOS_RETVAL_ERROR;
966                                             break;
967                                     }
968                                     grp = &grps[grps_num++];
>>>     CID 210449:  Memory - illegal accesses  (BUFFER_SIZE_WARNING)
>>>     Calling "strncpy" with a maximum size argument of 32 bytes on destination array "grp->name" of size 32 bytes might leave the destination string unterminated.

969                                     strncpy(grp->name, grp_name, DIM(grp->name));
970                                     grp->valid = 1;
971                             }
972                             if (!grp->valid)
973                                     continue;

**Comment by aleksinx** [comment]
The issue has been fixed by the following commit [https://github.com/intel/intel-cmt-cat/commit/192591a641f6fb1702d8b4d9ad7be0f9af062713](url)

**Comment by kmabbasi** [comment]
Hi Colin,

Thanks for reporting the issue

Like mentioned above this issue has been fixed. Therefore, going to close it now.

Thanks,
Khawar

**Comment by ColinIanKing** [comment]
many thanks! \o/
