### ISSUE TITLE
what is the meaning of COS MASK

### ISSUE THREAD

**Issue by jiangzh-acetrade** [intel/intel-cmt-cat#150]
INFO: L3 CAT details: CDP support=1, CDP on=0, #COS=16, #ways=11, ways contention bit-mask 0x600
INFO: L3 CAT details: cache size 25952256 bytes, way size 2359296 bytes
INFO: CPUID 0x10.0: L2 CAT not supported!
INFO: L2CA capability not detected
INFO: MBA capability detected
INFO: MBA details: #COS=8, linear, max=90, step=10
L3CA/MBA COS definitions for Socket 0:
    L3CA COS0 => MASK 0x7ff
    L3CA COS1 => MASK 0x1
    L3CA COS2 => MASK 0x7ff
    L3CA COS3 => MASK 0x7ff
    L3CA COS4 => MASK 0x7ff
    L3CA COS5 => MASK 0x7ff
    L3CA COS6 => MASK 0x7ff
    L3CA COS7 => MASK 0x7ff
    L3CA COS8 => MASK 0x7ff
    L3CA COS9 => MASK 0x7ff
    L3CA COS10 => MASK 0x7ff
    L3CA COS11 => MASK 0x7ff
    L3CA COS12 => MASK 0x7ff
    L3CA COS13 => MASK 0x7ff
    L3CA COS14 => MASK 0x7ff
    L3CA COS15 => MASK 0x7ff

how to caculate the cache size with MASK 0x7ff?
I guess this is mean the cache size or ways that allocated to each COS, if I want to change on COS, how do I know the new size or ways to set?

**Comment by kmabbasi** [comment]
Hi,

Based on provided information, total cache size = 25952256 bytes => ~26MB of 11 ways 
and 1 way size = 2359296 bytes => ~2.3MB

A bitmask of 0x7ff (default) allows full access to the cache since you know the size of 1 way by this you can calculate the new size of the mask. As an example a bitmask of 0x003, allows access to only the last two cache partitions, effectively, ~5MB (~2.3 x 2cache-ways).

Thanks,
Khawar

**Comment by jiangzh-acetrade** [comment]
Hi Khawar

 

Thanks for your reply, really help me 

 

But I still don’t understand what it the bitmask means, how should I calculate the exact way size? I mean 0X003 means the last two ways, 0x7ff is all 11 ways.

 

What is the rule in this convert?

 

Thanks！

 


蒋志红 / 硬件工程师 

Jiang / Hardware Engineer

 

ACETRADE®
High Frequency Application Server 

上海东融贸易有限公司 

-------------------------------

通信联系地址: 上海市浦东新区浦东大道1085号B座5楼-C   手机: 19921977817

 

发件人: kmabbasi <notifications@github.com> 
发送时间: 2020年5月23日 1:34
收件人: intel/intel-cmt-cat <intel-cmt-cat@noreply.github.com>
抄送: jiangzh-acetrade <jiangzh@acetrade.com.cn>; Author <author@noreply.github.com>
主题: Re: [intel/intel-cmt-cat] what is the meaning of COS MASK (#150)

 

Hi,

Based on provided information, total cache size = 25952256 bytes => ~26MB of 11 ways
and 1 way size = 2359296 bytes => ~2.3MB

A bitmask of 0x7ff (default) allows full access to the cache since you know the size of 1 way by this you can calculate the new size of the mask. As an example a bitmask of 0x003, allows access to only the last two cache partitions, effectively, ~5MB (~2.3 x 2cache-ways).

Thanks,
Khawar

**Comment by kmabbasi** [comment]
Hi Jiang,

The bitmask represents cache ways and the conversion was done from hex to binary bits:

All 11 ways: 0x7ff hex == 111 1111 1111 bits
Last 2 ways: 0x003 hex == 000 0000 0011 bits

1 means accessible cache way
0 means no access to cache way

You can find more details on [Intel SDM volume 3b Chapter 17 section 17.1 "Cache Allocation Techonology](https://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-software-developer-vol-3b-part-2-manual.html)"

Thanks,
Khawar

**Comment by jiangzh-acetrade** [comment]
Hi 

Thanks for your help, another question,

Is there any latency difference between cores to cache ways? Like core 1 is closer to way1 and far away from way11.

Sending from my iPhone

**Comment by kmabbasi** [comment]
No, Every LLC slice will contain 11 cache ways (CWs) so there is no latency difference between ways.
The HW determines which slice the CW is allocated into, this cannot be controlled by SW.

Thanks,
Khawar

**Comment by jiangzh-acetrade** [comment]
Thanks Khawar

You help me a lot! :D

Sending from my iPhone

> 在 2020年5月26日，下午8:50，kmabbasi <notifications@github.com> 写道：
> 
> Khawar

**Comment by kmabbasi** [comment]
Hi Jiang,

I am glad we are able to help you. By considering that your issue has been resolve I am going close to this issue.

Thanks,
Khawar

**Comment by jiangzh-acetrade** [comment]
Actually I’d like to delete this post if you can do it! :D

Sending from my iPhone

**Comment by kmabbasi** [comment]
Hi Jiang,

Unfortunately, we cannot fulfill your request of deleting this thread. The reason for using this forum is to help the community if they encounter similar issues. 

Thanks,
Khawar

**Comment by jiangzh-acetrade** [comment]
Thank you anyway !

Sending from my iPhone

**Comment by theUnspecified** [comment]
So nice of you that you have not deleted this issue @kmabbasi . This thread helped me a lot.
