### ISSUE TITLE
Error retrieving APICID info

### ISSUE THREAD

**Issue by Chinmay-Gupta** [intel/intel-cmt-cat#151]
Hi,
I'm facing issues with the program:
[root@slc13mwp view_storage]# pqos
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: Couldn't retrieve APICID structure information!ERROR: CPU topology detection error!ERROR: cpuinfo_init() error -14
Error initializing PQoS library!
[root@slc13mwp view_storage]# pqos -I
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: Couldn't retrieve APICID structure information!ERROR: CPU topology detection error!ERROR: cpuinfo_init() error -14
Error initializing PQoS library!
[root@slc13mwp view_storage]# pqos -s -V
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: Couldn't retrieve APICID structure information!ERROR: CPU topology detection error!ERROR: cpuinfo_init() error -14
Error initializing PQoS library!
[root@slc13mwp view_storage]# pqos -d
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: Couldn't retrieve APICID structure information!ERROR: CPU topology detection error!ERROR: cpuinfo_init() error -14
Error initializing PQoS library!

[root@slc13mwp view_storage]# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-4.14.35-1902.9.2.el7uek.x86_64 root=UUID=e1efd95f-0334-4dcd-8c47-15c078a39701 ro crashkernel=auto numa=off transparent_hugepage=never rdt=cmt,mbmtotal,mbmlocal,l3cat,l3cdp,l2cat,mba
[root@slc13mwp view_storage]# cat /boot/config-4.14.35-1902.9.2.el7uek.x86_64 | grep CONFIG_INTEL_RDT
CONFIG_INTEL_RDT=y

Please help me solve this issue. I seem to have installed my configuration correctly. Using an Intel(R) Xeon(R) CPU E5-2699C v4 @ 2.20GHz

**Comment by tkanteck** [comment]
Is 'pqos' tool executed within a virtual machine?

**Comment by Chinmay-Gupta** [comment]
Yes - is the tool not supposed to run from a VM ?

**Comment by tkanteck** [comment]
No, not really. I am not aware of any hypervisors allowing for RDT control from within a VM either through MSR or OS interface.
Maybe, just maybe, Xen allows for some control there.

**Comment by Chinmay-Gupta** [comment]
Okay - I'll try exploring Xen options. Thanks !

**Comment by tkanteck** [comment]
It is also interesting that the hypervisor used here doesn't support pretty standard CPUID leaf for APICID enumeration.
Good luck with Xen exploration! Please come back here and post results of your exploration.
