### ISSUE TITLE
How to fix Error os_cap_init() error 8

### ISSUE THREAD

**Issue by Chinmay-Gupta** [intel/intel-cmt-cat#152]
Hi,
Can you please help me with this error:

[root@vosamd7 pqos]# ./pqos -I -p all:4364
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: OS interface selected but not supported
ERROR: os_cap_init() error 8
Error initializing PQoS library!

[root@vosamd7 pqos]# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-4.4.214-1.el7.elrepo.x86_64 root=/dev/mapper/centos-root ro crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet intel_idle.max_cstate=0 selinux=0 numa=off transparent_hugepage=never rdt=cmt,mbmtotal,mbmlocal,l3cat

No configuration is set in /boot/config... because the kernel is 4.4 and before 4.10. 
Processor is Intel(R) Xeon(R) Platinum 8260L CPU @ 2.40GHz

Going through the source code, I couldn't figure out the problem. Any help would be appreciated !

**Comment by tkanteck** [comment]
This line "ERROR: OS interface selected but not supported" suggests that OS interface is enforced (perhaps through environment setting). Kernel 4.4 is in use. When you look into Table 3 of README https://github.com/intel/intel-cmt-cat/blob/master/README#L229 you'll notice that 4.14 is the minimum kernel version for full OS control over RDT.

**Comment by njjry** [comment]
Hi,
I have the same issue with the same processor but the kernel version is 4.14.81 which meets the minimum kernel version. Why do I still have this issue? In the configuration file, the CONFIG_INTEL_RDT is set to y. Any help would be appreciated!

**Comment by kmabbasi** [comment]
Can you please send us the output of the following:

`sudo pqos -I -D`
`sudo pqos -I -sV`
`cat /proc/cmdline`

Thanks,
Khawar

**Comment by njjry** [comment]
Hi Khawar,

Thanks for the prompt reply,

Here is the output of the commands:

sudo pqos -I -D:

NOTE:  Mixed use of MSR and kernel interfaces to manage

       CAT or CMT & MBM may lead to unexpected behavior.

ERROR: OS interface selected but not supported

ERROR: os_cap_init() error 8

Error initializing PQoS library!

sudo pqos -I -sV:

NOTE:  Mixed use of MSR and kernel interfaces to manage

       CAT or CMT & MBM may lead to unexpected behavior.

INFO: CACHE: type 1, level 1, max id sharing this cache 1 (1 bits)

DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size
64, 1 partition(s)

INFO: CACHE: type 2, level 1, max id sharing this cache 1 (1 bits)

DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size
64, 1 partition(s)

INFO: CACHE: type 3, level 2, max id sharing this cache 1 (1 bits)

DEBUG: CACHE: not inclusive, direct mapped, 16 way(s), 4096 set(s), line
size 64, 1 partition(s)

INFO: CACHE: type 3, level 3, max id sharing this cache 8 (3 bits)

DEBUG: CACHE: inclusive, complex cache indexing, 16 way(s), 16384 set(s),
line size 64, 1 partition(s)

DEBUG: Detected core 0, socket 0, L2 ID 0, L3 ID 0, APICID 0

DEBUG: Detected core 1, socket 0, L2 ID 0, L3 ID 0, APICID 1

DEBUG: Detected core 2, socket 0, L2 ID 1, L3 ID 0, APICID 2

DEBUG: Detected core 3, socket 0, L2 ID 1, L3 ID 0, APICID 3

DEBUG: Detected core 4, socket 0, L2 ID 2, L3 ID 0, APICID 4

DEBUG: Detected core 5, socket 0, L2 ID 2, L3 ID 0, APICID 5

DEBUG: Detected core 6, socket 0, L2 ID 3, L3 ID 0, APICID 6

DEBUG: Detected core 7, socket 0, L2 ID 3, L3 ID 0, APICID 7

INFO: resctrl not detected. Kernel version 4.10 or higher required

ERROR: OS interface selected but not supported

ERROR: os_cap_init() error 8

Error initializing PQoS library!

cat /proc/cmdline:

BOOT_IMAGE=/boot/vmlinuz-4.14.81.bm.15-amd64
root=UUID=b0304aae-86bf-46b8-a80c-3c723398d957 ro cgroup_enable=memory
swapaccount=1 net.ifnames=0 biosdevname=0 transparent_hugepage=madvise
nokaslr console=tty0 console=ttyS0,115200 crashkernel=1G-:256M


Thanks
-- Runyu

**Comment by kmabbasi** [comment]
Thanks for providing the output.

Please note that RDT works only on Host NOT on VMs/Containers. Could you please confirm that the you are not running RDT on VMs/Containers?

Thanks,
Khawar

**Comment by njjry** [comment]
It is running on VM. Thanks

**Comment by kmabbasi** [comment]
RDT doesn't work on VMs. You can try it on host and let us know if you find any issues. 
By now I am going to close this issue.

Thanks,
Khawar
