### ISSUE TITLE
pqos -I -p monitoring start error,status 7

### ISSUE THREAD

**Issue by lionelee** [intel/intel-cmt-cat#158]
when I tried `pqos -I -p all:29074`, I got the errors as below:
```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: Failed to create resctrl monitoring group!
ERROR: Failed to start all selected OS monitoring events
PID 29074 monitoring start error,status 7
```
_the output of `pqos -v` is:_

NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
INFO: CACHE: type 1, level 1, max id sharing this cache 2 (1 bits)
INFO: CACHE: type 2, level 1, max id sharing this cache 2 (1 bits)
INFO: CACHE: type 3, level 2, max id sharing this cache 2 (1 bits)
INFO: CACHE: type 3, level 3, max id sharing this cache 64 (6 bits)
WARN: resctl filesystem mounted! Using MSR interface may corrupt resctrl filesystem and cause unexpected behaviour
INFO: Monitoring capability detected
INFO: CPUID.0x7.0: L3 CAT supported
INFO: L3 CDP is disabled
INFO: L3CA capability detected
INFO: L3 CAT details: CDP support=1, CDP on=0, #COS=16, #ways=11, ways contention bit-mask 0x600
INFO: L3 CAT details: cache size 25952256 bytes, way size 2359296 bytes
INFO: CPUID 0x10.0: L2 CAT not supported!
INFO: L2CA capability not detected
INFO: MBA capability detected
INFO: MBA details: #COS=8, linear, max=90, step=10

_kernel version is 4.18.0_

**Comment by lionelee** [comment]
I used `taskset -c`

**Comment by mdcornu** [comment]
Please refer to [this ](https://github.com/intel/intel-cmt-cat/issues/73#issuecomment-391280889) previous issue with details of a similar problem where these events are disabled in the kernel by default.
Our [wiki ](https://github.com/intel/intel-cmt-cat/wiki#enabling-intelr-rdt-support-in-the-linux-kernel-os-interface) outlines how to re-enable these events.

Let us know if this does not solve the problem.

Regards,
Marcel

**Comment by lionelee** [comment]
Thanks for your help!
But I solved it with `umount resctrl`

**Comment by packagewjx** [comment]
I ran into this problem, too. I found that there are lots of folders under /sys/fs/resctrl/mon_groups, so I suspected that no more monitoring groups can be created. So I ran `pqos -I -r` to reset monitoring, and it worked.
