### ISSUE TITLE
/var/lock/libpqos is not deleted when pqos exits with an error when msr module not loaded

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-cmt-cat#159]
I forgot to load the msr module, I ran pqos and found that /var/lock/libpqos was not removed:

sudo pqos
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: Error opening file '/dev/cpu/0/msr'!
ERROR: L3 CDP detection error!
ERROR: Fatal error encounter in L3 CAT discovery!
ERROR: discover_capabilities() error 1
Error initializing PQoS library!
ubuntu@cool-beagle:~$ ls -al /var/lock/libpqos 
-rw-r--r-- 1 root root 0 Jun 30 08:52 /var/lock/libpqos

I believe the lock file should be removed when pqos terminates.

**Comment by kmabbasi** [comment]
Thanks Colin for reporting this issue.

We will investigate this soon.

Thanks again,
Khawar

**Comment by kmabbasi** [comment]
Hi Colin,
No, we cannot remove the lock file when pqos terminates because we are supporting multiple instances of lib running in parallel. If one instance removes this, it may affect other instances that depend on this lock file.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
Hi Colin,
I am going to close this issue now.

Thanks,
Khawar
