### ISSUE TITLE
How to know the  memory bandwidth of CPU cores? 

### ISSUE THREAD

**Issue by sming56** [intel/intel-cmt-cat#161]
Form "pqos -T" output, I can know the memory access speed of the the cpu cores.  But how can I know if it reached the memory bandwidth uplimit?

TIME 2020-07-22 18:14:41
    CORE         IPC      MISSES     LLC[KB]   MBL[MB/s]   MBR[MB/s]
      19        0.76       7039k      4800.0       441.6       231.9  <--- Does it reach the memory bandwidth uplimit?
      11        0.68       5516k      4272.0       341.9       388.1
      13        0.70       7546k      4176.0       528.5       243.5
      17        0.78       7044k      2688.0       409.1       240.8
      24        1.02       6376k      2688.0       384.2       265.8
      29        0.76       6755k      2496.0       369.8       288.7
      30        0.80       4261k      2496.0       256.1       191.0
      25        0.80       6886k      2400.0       376.2       296.7
      31        1.04       6388k      1968.0       334.7       267.0
      26        0.82       7192k      1920.0       392.4       337.8
      40        0.71       4293k      1920.0       273.2       181.3
      10        0.90       5203k      1728.0       277.6       242.5
      21        0.70       7161k      1680.0       443.6       211.8
      14        0.71       7708k      1584.0       409.1       277.5
      18        0.73       7475k      1536.0       483.0       223.6
      22        0.81       7019k      1488.0       461.2       184.8
       9        0.70       5990k      1440.0       337.2       288.0
      15        0.75       8133k      1344.0       544.8       226.4
      47        0.84       5215k      1296.0       320.6       197.8
      27        0.93       6695k      1248.0       361.8       287.1
      32        0.69       3103k      1152.0       154.7       148.8
      12        0.75       7166k      1104.0       458.1       216.2
      23        0.67       6913k      1104.0       450.5       202.2
      35        0.83       3241k      1008.0       194.8       138.6
       4        0.46        829k       960.0        57.1        22.6
      34        1.11       3533k       864.0       208.5       167.5
      33        0.74       3700k       816.0       237.0       152.2
      46        0.90       5060k       768.0       277.6       227.5
       8        0.73       5028k       720.0       261.6       236.5
      44        0.64       4773k       720.0       324.2       116.9
      28        0.97       7007k       672.0       412.3       302.0

**Comment by mdcornu** [comment]
Hi,

Please have a look at issue #109.
If you have any other questions, let me know.

Regards,
Marcel

**Comment by kmabbasi** [comment]
Hi,

It's been more than 3 weeks that we didn't hear you back. Therefore, I am going to close this issue now.

Feel free to re-open/create new if you have any query.

Thanks,
Khawar
