### ISSUE TITLE
Will pqos be available on virtual machines (KVM)?

### ISSUE THREAD

**Issue by Mike03-Sullivan** [intel/intel-cmt-cat#162]
Referring to issue #151 ("Error retrieving APICID info"), where Tomasz Kantecki said RDT does not work in a virtual environment (except possibly Xen):  I had the same problem until I read issue #151.  I use two cloud services, both using KVM.  Are there any plans to  make RDT available in a KVM virtual environment?  Most of the clients who use our software run in the cloud as well, and it would be very useful in that environment.  

I also note that https://software.intel.com/content/www/us/en/develop/articles/cache-allocation-technology-usage-models.html says:  

"How Does CAT Work?
Low-level software such as an OS or VMM uses the CAT feature via the following steps . . . "

In https://software.intel.com/content/www/us/en/develop/articles/introduction-to-cache-allocation-technology.html it says:

"What is Cache Allocation Technology (CAT?)?
Cache Allocation Technology (CAT) provides software-programmable control over the amount of cache space that can be consumed by a given thread, app, VM, or container." 

And https://www.intel.com/content/www/us/en/architecture-and-technology/resource-director-technology.html says:
"Intel® Resource Director Technology (Intel® RDT) brings new levels of visibility and control over how shared resources such as last-level cache (LLC) and memory bandwidth are used by applications, virtual machines (VMs), and containers." 

So those links imply that RDT does work in a virtual environment.  But I got the same error as in Issue #151.  

Thanks.  

Mike Sullivan

**Comment by tkanteck** [comment]
Hello Mike,

Thanks reaching out.

Correct, RDT works in virtual environment but, as you wrote, at VMM/hypervisor level. VMM can assign some pool of resources to a virtual machine without allowing the machine to manage it internally. In this way VM's can be prioritized so to say.

Enabling it in a way that allows VM to manage resources internally requires a few problems to be solved and not all of them are technical:
- Cloud service providers need to allow for it and build business model around it: amount of CPU resources assigned to an instance, cache shared/exclusive, memory bandwidth, pricing etc. It does complicate product offer, pricing and also brings new level of complexity for customer support.
- Plumbing in VMM's/hypervisors and/or in OS kernels to operate as expected within a VM

So far I haven't come across a use case that requires managing CPU resources within a VM. Could you share what kind/class of application requires it?

Thanks,
Tomasz

**Comment by kmabbasi** [comment]
Hi Mike,

It's been more than 3 weeks we didn't hear from you. 

I am going to close this issue by considering you got the answer.

Thanks,
Khawar
