### ISSUE TITLE
About the output format of pqos command

### ISSUE THREAD

**Issue by sming56** [intel/intel-cmt-cat#163]
Please check the "pqos" command output below.  I got several questions about the output format of pqos.
1) What does "MISSES" mean?
   Is it the total missing of L1 cache but hitting L2 cache?
2) What odes "LLC" mean?
   Is  it the total missing of L2 cache but hitting last level cache(L3)?
3) Does MBL+MBR mean the total missing of LLC?
--------
TIME 2020-07-28 18:26:01
    CORE         IPC      MISSES     LLC[KB]   MBL[MB/s]   MBR[MB/s]
      18        0.94       9013k      1584.0       534.0        21.8
      27        0.92       3117k      1536.0       172.4        51.5
      23        0.98       9286k      1440.0       589.5        29.4
       8        0.77       7408k      1296.0       439.1        71.6
      10        0.73       5872k      1296.0       360.8        29.1
       3        0.62       7630k      1200.0       453.7        45.1
       5        0.62       7943k      1200.0       481.3        45.8
       7        0.64       8233k      1200.0       415.6        97.1
      47        0.90       5293k      1200.0       307.6        12.8
      41        0.83       4679k      1152.0       277.8        16.5
      15        0.99       8802k      1056.0       535.5        21.0
      19        1.04       9285k      1056.0       563.8        20.6
       4        0.76       8567k      1008.0       501.7        54.1
       1        0.62       7301k       960.0       402.5        50.8
       2        0.68       8355k       912.0       476.2        91.2
      24        0.69       2494k       912.0       140.1        38.8
      14        1.09       9025k       864.0       546.1        28.2
      20        1.14      10913k       864.0       658.2        27.5
      16        1.07       9005k       816.0       539.3        23.0
      31        0.84       2653k       816.0       132.6        50.3
      26        0.84       2670k       672.0       147.6        38.5
       6        0.70       8551k       624.0       465.8        45.6
      13        1.04       9033k       624.0       531.9        29.2

**Comment by kmabbasi** [comment]
Hi,

1. This is an architectural performance monitoring event, which counts each cache miss condition for references to the last level on-die cache

2. LLC column relates to CMT which monitors cache occupancy on per-thread basis i.e. how much cache is occupied (in bytes)

3. No, this is not the total missing of LLC. It's memory bandwidth

Thanks,
Khawar

**Comment by sming56** [comment]
> Hi,
> 
> 1. This is an architectural performance monitoring event, which counts each cache miss condition for references to the last level on-die cache
Sure.  In a common CPU,  last level on die cache is the L2 cache. Right?  If so, "MISSES" means the number of bytes of cache miss condition  to L2 cache and go to LLC finally?

> 2. LLC column relates to CMT which monitors cache occupancy on per-thread basis i.e. how much cache is occupied (in bytes)
I was wondering that what is "per-thread basis".  Does that mean the thread running on the CPU core or ?  For example, the first row shows  "1584.0K" LLC, does that mean the current thread on cpu 18 occupy 1584.0K bytes of LLC?

> 3. No, this is not the total missing of LLC. It's memory bandwidth
I was wondering why the memory bandwidth was much larger in bytes than the MISSES numbers.  IMO, only "MISSES" can go to the memory bandwidth or does that mean many instructions there  went to the memory bandwidth without snooping the cache?

> 
> Thanks,
> Khawar

**Comment by kmabbasi** [comment]
1. No, the last level on die cache for Intel(R) Xeon(R) processor is the L3 cache. This is the number of LLC misses that will result in loads from memory.

2. this refers to HW thread for example if Hyperthreading is enabled 1 physical core will have 2 logical cpus/threads. In the above case, core/logical cpu(18) occupies 1584.0K of LLC.

3. MISSES reports the number of LLC misses, not the bytes.

Thanks,
Khawar

**Comment by sming56** [comment]
Khawar,
Thanks for your kindly reply.

> 3. MISSES reports the number of LLC misses, not the bytes.

Then this equation "(MISSSES * 64 bytes) = (MBL + MBR) * BYTES_PER_MEGA" should  be true.  I suppose the the cache line is 64 byte aligned.  However, based on  the pqos output pasted above, this equation is not true.
BTW:  The MISSES is the number of LLC missing in 1 second
for example, on logical core 18, 
(9013K * 64 ) = 576832K
(534.0M + 21.8M) * 1024K =  569139.2K 
569139.2K < 576832K
So (MISSSES * 64 bytes) >  (MBL + MBR) * BYTES_PER_MEGA

on logical 27,
(3117K * 64) = 199488K
( 172.4 +  51.5) * 1024K= 229273.6K
229273.6K > 199488K
So (MISSSES * 64 bytes) <  (MBL + MBR) * BYTES_PER_MEGA

The two numbers are near but not exactly the same.  The left side of the equation can be larger or smaller than the right side.  Please correct me for any reason.

> 
> Thanks,
> Khawar

**Comment by kmabbasi** [comment]
Hi,

The equation (mentioned above) could be used as an approximation but is unlikely to be perfectly accurate since actual B/W generated depends on many factors such as the workload, memory traffic type, processor generation, etc.

e.g. A LLC miss could result in a single load, or a store (CL write back) followed by a load depending on the state of the cache line being evicted and both loads & stores will be counted as B/W.

**Comment by kmabbasi** [comment]
We haven't heard anything back from you. We are going to close this issue by considering your issue has been resolved.

Thanks,
Khawar
