### ISSUE TITLE
Found a bunch of spelling mistakes 

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-cmt-cat#164]
Found a bunch of spelling mistakes with the codespell tool.  Can these be fixed?

./rdtset/common.h:160: configuretion ==> configuration
./tests/.pylintrc:52: reenable ==> re-enable
./tests/README.txt:35: enviroment ==> environment
./tests/README.txt:43: assummed ==> assumed
./tests/plugins/pytest_report.py:133: intersted ==> interested
./tests/schema/env.json:4: Enviroment ==> Environment
./tests/schema/env.json:41: fo ==> of, for
./tests/schema/env.json:65: fo ==> of, for
./examples/python/monitoring.py:72: supproted ==> supported
./pqos/pqos-os:39: utilty ==> utility
./pqos/pqos-os:42: utilty ==> utility
./pqos/main.c:713: Process' ==> Process's
./pqos/pqos.8:201: Process' ==> Process's
./pqos/pqos-msr:39: utilty ==> utility
./pqos/pqos-msr:42: utilty ==> utility
./pqos/monitor.c:182: Mantains ==> Maintains
./.git/logs/HEAD:17: severeal ==> several
./.git/logs/HEAD:45: Trival ==> Trivial
./.git/logs/HEAD:61: suported ==> supported
./.git/logs/refs/heads/master:17: severeal ==> several
./.git/logs/refs/heads/master:45: Trival ==> Trivial
./.git/logs/refs/heads/master:61: suported ==> supported
./appqos/.pylintrc:52: reenable ==> re-enable
./appqos/pid_ops.py:42: unning ==> running
./appqos/tests/test_rest_pool.py:393: unknonw ==> unknown
./lib/resctrl_monitoring.c:86: breif ==> brief
./lib/resctrl_monitoring.c:1028: Assignes ==> Assigns
./lib/os_monitoring.c:532: numer ==> number
./lib/os_allocation.c:569: entires ==> entries
./lib/os_allocation.c:672: requsted ==> requested
./lib/os_allocation.c:711: requsted ==> requested
./lib/os_allocation.c:750: requsted ==> requested
./lib/cap.c:141: Initalizes ==> Initializes
./lib/cap.h:79: Aquires ==> Acquires
./lib/python/.pylintrc:52: reenable ==> re-enable
./lib/python/pqos/monitoring.py:191: defualt ==> default
./lib/python/pqos/monitoring.py:215: defualt ==> default
./lib/python/pqos/pqos.py:127: additonal ==> additional
./lib/python/pqos/test/test_capability.py:69: neccessary ==> necessary
./lib/python/pqos/test/test_capability.py:82: neccessary ==> necessary
./lib/python/pqos/test/test_capability.py:94: neccessary ==> necessary
./lib/python/pqos/test/test_capability.py:106: neccessary ==> necessary
./lib/python/pqos/test/test_capability.py:117: capabilites ==> capabilities
./lib/python/pqos/test/test_capability.py:127: capabilites ==> capabilities

**Comment by kmabbasi** [comment]
Hi Colin,

Thanks for reporting this.

We are working on this so to avoid spelling mistakes in the future. 

Thanks,
Khawar

**Comment by ColinIanKing** [comment]
Thanks! Much appreciated.
