### ISSUE TITLE
Travis-ci: Build is failing on AMD64 due to codespell

### ISSUE THREAD

**Issue by sanjaymsh** [intel/intel-cmt-cat#167]
Hi,

The travis-ci build is failing on AMD with below error:

"make[2]: codespell: Command not found
Makefile:243: recipe for target 'codespell' failed
make[2]: *** [codespell] Error 127
make[2]: Leaving directory '/home/travis/build/sanjaymsh/intel-cmt-cat/lib'
Makefile:247: recipe for target 'style' failed
make[1]: *** [style] Error 2
make[1]: Leaving directory '/home/travis/build/sanjaymsh/intel-cmt-cat/lib'
Makefile:73: recipe for target 'style' failed
make: *** [style] Error 2
The command "make style CHECKPATCH=/tmp/checkpatch.pl CLANGFORMAT=clang-format-9" exited with 2."

Seems that codespell is not found.

Here is the full log: https://travis-ci.com/github/sanjaymsh/intel-cmt-cat/builds/190445573

Please look into this.

Thanks !!

**Comment by kmabbasi** [comment]
Thanks Sanjay for reporting this issue.

It has been resolved now.

-Khawar
