### ISSUE TITLE
Can MBA be used for allocating NVM bandwidth?

### ISSUE THREAD

**Issue by sherlockwu** [intel/intel-cmt-cat#170]
Hi there,

Sorry for if this is not the perfect place to ask. 

But, can MBA be used for allocating Optane DC Persistent Memory bandwidth? 
Moreover, if we do not want to allocate DRAM bandwidth, but only DC Persistent Memory bandwidth, is that doable?

Thanks,
Kan

**Comment by kmabbasi** [comment]
Hi Kan,

Unfortunately no, as MBA throttles memory as a whole 

Thanks,
Khawar

**Comment by sherlockwu** [comment]
Thanks for clarification!
