### ISSUE TITLE
ModuleNotFoundError: No module named 'pqos'

### ISSUE THREAD

**Issue by Yxiaoge** [intel/intel-cmt-cat#175]
I tried to run the example under /example/python
But got “ModuleNotFoundError: No module named 'pqos'”
what should i do?

**Comment by amoksyakov** [comment]
Hello,
you can try to use the following:  

export PYTHONPATH=/home/amoksyakov/intel-cmt-cat/lib/python/pqos/pqos.py   
./env/bin/python monitoring.py -h  
usage: monitoring.py [-h] [-I] [-p] CORE/PID [CORE/PID ...]  
  
PQoS Library Python wrapper - monitoring example  
  
positional arguments:  
  CORE/PID    a core or PID to be monitored  
  
optional arguments:  
  -h, --help  show this help message and exit  
  -I          select library OS interface  
  -p, --pid   select PID monitoring

**Comment by kmabbasi** [comment]
Hi,
This error is because of python wrapper. 
To resolve dependency of python wrapper please see below link 
https://github.com/intel/intel-cmt-cat/wiki/FAQ#how-to-install-libpqos-python-wrapper 

Thanks,
Khawar

**Comment by kmabbasi** [comment]
We haven't heard anything back. Therefore, we are going to close this issue by considering it has been resolved.

Thanks,
Khawar
