### ISSUE TITLE
MBA is inaccurate in Intel® Xeon® Gold 6338N CPU

### ISSUE THREAD

**Issue by whytehuang** [intel/intel-cmt-cat#176]
**some information for my test environment**

1. OS information and kernel version
Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-65-generic x86_64)
2. cpu information
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Gold 6338N CPU @ 2.20GHz
Stepping:                        6
CPU MHz:                         2804.250
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4400.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitizatio
                                 n
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat p
                                 se36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdp
                                 e1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl
                                  xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monito
                                 r ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse
                                 4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16
                                 c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 in
                                 vpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi
                                  flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bm
                                 i2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512if
                                 ma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsave
                                 opt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_m
                                 bm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_ep
                                 p hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpcl
                                 mulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clea
                                 r pconfig flush_l1d arch_capabilities
3. **memory information**
Number Of Devices: 16
Size: 16 GB
Type: DDR4
Speed: 3200 MT/s
Manufacturer: Adata
Configured Memory Speed: 3200 MT/s

**testing method**

1. Create VM CentOS to stress(stress-ng --stream 1 --stream-l3-size 8M)
2. Use command: modprobe msr  & pqos -r     to check MBL
3. Use command: pqos –e mba:1=50 & pqos –a llc:1=0    to set MBL to 50%
4. But found MBL from 17800 to 16000, can't down down to 50%.

Does Intel-cmt-cat( version 4.1)'s MBA function support ICX ?

**Comment by kmabbasi** [comment]
Is your stress-ng (VM) running only on core 0? In this MBA only throttles on core0.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
We haven't heard anything back from you. We are going to close this issue by considering it has been resolved.

Thanks,
Khawar
