### ISSUE TITLE
No /sys/fs/resctrl found with updated kernel?

### ISSUE THREAD

**Issue by oleotiger** [intel/intel-cmt-cat#179]
I wanna use cat/mba.
OS:Centos7.6
My pre kernel version is Linux 3.10.0-957.el7.x86_64 x86_64
So I update it to Linux 5.11.9-1.el7.elrepo.x86_64 x86_64.

With 3.10.0 I can find /sys/fs/resctrl. But when updated to 5.11.9 I can't find resctrl under /sys/fs.

So How could I use resctrl?

What's more, in kernel .config, there is no more configurations like INTEL_RDT of kernel 5.11.9, so should I leave configurting it and just use rdt?

**Comment by dxlet** [comment]
hello, I encountered the same problem. Could you explain how you solved it? Thank you!!!
