### ISSUE TITLE
How to use resctrl on centos7.6(kernel 3.10)?

### ISSUE THREAD

**Issue by oleotiger** [intel/intel-cmt-cat#180]
I have reading the wiki about [resctrl](https://github.com/intel/intel-cmt-cat/wiki/resctrl).

It mentions that    'If you wish to use this before the release of kernel 4.10 you can download from here [kernel.googlesource x86/cache](https://kernel.googlesource.com/pub/scm/linux/kernel/git/tip/tip/+/x86/cache)'

I go into the link and find that this is a commit to linux kernel with 2 files:arch/x86/include/asm/resctrl.h and
arch/x86/kernel/cpu/resctrl/rdtgroup.c.

But with source code of my kernel of version 3.10 there is no directory arch/x86/kernel/cpu/resctrl at all.

Does it mean that I need to update my kernel source code with these 2 files and recompile kernel and install it?

**Comment by kmabbasi** [comment]
Hi,

We tested our latest release on specific versions of RedHat kernel for validation and it works fine.

To the best of my knowledge it should work on RHEL 7.9 which is a 3.10 backported kernel.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
This issue has been discussed on another thread. Therefore, I am going to close it now.
https://github.com/intel/intel-cmt-cat/issues/183

Thanks,
Khawar
