### ISSUE TITLE
Are the MBA parameters configured for each core or for each COS?

### ISSUE THREAD

**Issue by dxlet** [intel/intel-cmt-cat#185]
Hello everyone!

> MBA bandwidth limits per-CLOS are specified as a value in the range of zero to a maximum supported level of throttling for the **platform**

I learn from some documents that MBA can limit the bandwidth for each COLS, but in my experiment, MBA limits the bandwidth for each core not COLS.

The maxium memory bandwidth of my platform is about 40GB/s which is tested by mlc appliction

Firstly, I run _stream_ on 10 cores without any rdt configuration
```
OMP_NUM_THREADS=10 ./stream_c.exe &
taskset -acp 0-9 pid
```
![image](https://user-images.githubusercontent.com/21816834/116001107-7f058100-a625-11eb-857e-7a3e4ade04d0.png)

This application spent a total of about 20GB/s of bandwidth (50% of maxium bandwidth). Then，I constrained 0-9 cores to only use 10% of the memory bandwidth, but cannot limit their memory bandwidth.

```
pqos -e "mba:1=10"
pqos -a "core:1=0-9"
```
![image](https://user-images.githubusercontent.com/21816834/116001483-3e0e6c00-a627-11eb-80c4-2b20a6e15343.png)

Secondly, I run _stream_ on 3 cores without any rdt configuration. Only when the bandwidth of each core is large enough, my constraints can be reflected. 
![image](https://user-images.githubusercontent.com/21816834/116001494-54b4c300-a627-11eb-8918-bf621576e31b.png)

```
pqos -e "mba:1=10"
pqos -a "core:1=1-10"
```
![image](https://user-images.githubusercontent.com/21816834/116001284-487c3600-a626-11eb-92d9-b89adbf38e60.png)

From this experiment, the MBA parameter is to constrain the memory bandwidth of **each core** rather than **each CLOS**.

I also tried the -I option to use the OS interface, and also tried to use -p to specify the pid to allocate, and I got the same result.
Is the result as expected? Or is my operation wrong?

My platform information：
Kernel: 5.11.16
OS: centos-release-7-9.2009
CPU: Intel Xeon gold 6278C.

**Comment by kmabbasi** [comment]
This is expected behavior. The MBA delay values are per CLOS. That delay value will be applied to every core associated with that CLOS.
In your case, looks like 10% bandwidth generates approximately 2GB/s. So for 10 cores, its 20G.

**Comment by dxlet** [comment]
Thanks! I want to restrict the memory bandwidth more strictly (e.g. 1GB/s). Is there a way to achieve this goal? Even bypass pqos or resctrl, directly write MSR.

**Comment by kmabbasi** [comment]
Yes, you could use MBA SW controller.
https://github.com/intel/intel-cmt-cat/wiki/MBM-MBA-how-to-guide#mba---mbm---configure-mba-in-mbs

Thanks,
Khawar

**Comment by dxlet** [comment]
I tried MBA SW controller. It can limit the memory bandwidth to 2600MB/s at least,  and it cannot limit the memory bandwidth to a lower value. Is this normal？

**Comment by kmabbasi** [comment]
SW controller allows you to provide values in MB/s. It doesn't provide more throttling than MBA values in % does.
