### ISSUE TITLE
Can the MBM feature moniter memory bandwidth caused by DMA? 

### ISSUE THREAD

**Issue by Jiangrijin** [intel/intel-cmt-cat#186]
I want to moniter VM's memory bandwidth, so I wonder if the output of MBM(Memory Bandwidth Monitering) includes DMA's bandwidth like network bandwidth.

**Comment by mdcornu** [comment]
MBM only counts bandwidth generated by processor cores, so the MBM output will not include DMA bandwidth.

**Comment by Jiangrijin** [comment]
Thanks a lot! I also want to know if the output covers both read and write memory bandwidth.

**Comment by mdcornu** [comment]
Yes, reads and writes are counted by MBM.
