### ISSUE TITLE
Error initializing PQoS library on AWS c5.metal/r5.metal instance

### ISSUE THREAD

**Issue by SenRamakri** [intel/intel-cmt-cat#190]
I'm seeing the below error when trying to run "sudo pqos -s" on an AWS c5.metal instance. Is this a known issue? How can I get intel-cmt-cat working?

~$ sudo pqos -s
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
**API lock initialization error!
Error initializing PQoS library!**

The OS on that machine is Ubuntu 20.04.2 LTS(kernel version 5.4.0). And the CPU on that instance is Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz. And I have verified that "msr" driver is loaded.

**Comment by kmabbasi** [comment]
Hi Ramakrishnan,

When pqos library initializes, it creates libpqos file in /var/lock directory. It looks like permission issue.

Can you check libpqos is present in /var/lock directory? if not, try below command to check permissions are ok.

sudo touch /var/lock/libpqos

Also can you confirm you are not using VM or container?

Thanks,
Khawar

**Comment by kmabbasi** [comment]
Would it be possible for you to try manually deleting that lock file and run pqos again?

Thanks,
Khawar

**Comment by SenRamakri** [comment]
@kmabbasi - Deleting the lock file before running pqos seems to have fixed the problem. Now I see the below output when doing "sudo pqos -s". Thanks for your help with this issue.

NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
L3CA/MBA COS definitions for Socket 0:
    L3CA COS0 => MASK 0x7ff
    L3CA COS1 => MASK 0x7ff
    L3CA COS2 => MASK 0x7ff
    L3CA COS3 => MASK 0x7ff
    L3CA COS4 => MASK 0x7ff
    L3CA COS5 => MASK 0x7ff
    L3CA COS6 => MASK 0x7ff
    L3CA COS7 => MASK 0x7ff
    L3CA COS8 => MASK 0x7ff
    L3CA COS9 => MASK 0x7ff
    L3CA COS10 => MASK 0x7ff
    L3CA COS11 => MASK 0x7ff
    L3CA COS12 => MASK 0x7ff
    L3CA COS13 => MASK 0x7ff
    L3CA COS14 => MASK 0x7ff
    L3CA COS15 => MASK 0x7ff
    MBA COS0 => 100% available
    MBA COS1 => 100% available
    MBA COS2 => 100% available
    MBA COS3 => 100% available
    MBA COS4 => 100% available
    MBA COS5 => 100% available
    MBA COS6 => 100% available
    MBA COS7 => 100% available
...

**Comment by kmabbasi** [comment]
I am glad, your issue has been resolved!

Thanks,
Khawar
