### ISSUE TITLE
pqos stop cleanly on SIGINT or Ctrl + C,  but leave garbage files on SIGTERM

### ISSUE THREAD

**Issue by guoqiao** [intel/intel-cmt-cat#197]
while testing the [telegraf intel RDT plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/intel_rdt/README.md), we noticed pqo process will stop cleanly with Ctrl + C, or `kill -SIGINT $PID`.  However, it leaves garbage files on disk with `kill $PID`  (kill sends -SIGTERM by default). 

How to reproduce:

on ubuntu 18.04/20.04, with required CPU, and intel-cmt-cat installed:

sudo -i
cd /sys/fs/resctrl/mon_groups

/usr/sbin/pqos -r --iface-os --mon-file-type=csv --mon-interval=10 --mon-core=all:[0,1]\;mbt:[0,1]\;

1. run above cmd, close it with Ctrl + C or `kill -SIGINT $PID`,  then `ls`, no files left.
2. run cmd again, `ps -ef | grep pqos` to get $PID, run `kill $PID`,  you can see garbage files like this:

```
/sys/fs/resctrl/mon_groups# tree .
.
└── pqos-28194-0
    ├── cpus
    ├── cpus_list
    ├── mon_data
    │   └── mon_L3_00
    │       ├── llc_occupancy
    │       ├── mbm_local_bytes
    │       └── mbm_total_bytes
    └── tasks
```

NOTE:  if run cmd again,  above dir will be deleted, new dir like pqos-$PID-0 will be generated. 

For the background of this issue, please refer to #198

**Comment by kmabbasi** [comment]
Thanks for the feedback.

We have pushed a fix on master branch. It usually takes few hours to be shown on GitHub.

Can you try it again later today or tomorrow?

Thanks,
Khawar

**Comment by guoqiao** [comment]
> Thanks for the feedback.
> 
> We have pushed a fix on master branch. It usually takes few hours to be shown on GitHub.
> 
> Can you try it again later today or tomorrow?
> 
> Thanks, Khawar

Hi @kmabbasi   thanks for the quick response 💯
