### ISSUE TITLE
[seek for advice] how to close pqos cleanly as non-root user

### ISSUE THREAD

**Issue by guoqiao** [intel/intel-cmt-cat#198]
This issue is created to seek for advice from pqos official team.

Our team is trying to use [telegraf intel RDT plugin] (https://github.com/influxdata/telegraf/blob/master/plugins/inputs/intel_rdt/README.md) on ubuntu servers in production.

pqos must run as root, but telegraf is running on ubuntu as non-root user `telegraf`.
We are able to let telegraf start pqos with a sudoer file rule, e,g:

```
cat /etc/sudoers.d/telegraf_intel_rdt
Cmnd_Alias PQOS = /usr/sbin/pqos -r --iface-os --mon-file-type=csv --mon-interval=*
telegraf ALL=(root) NOPASSWD: PQOS
Defaults!PQOS !logfile, !syslog, !pam_session
```
However,  we have trouble to let telegraf shutdown pqos when `service telelegraf stop` or RDT plugin disabled.
We had discussions in [telegraf #9527](https://github.com/influxdata/telegraf/pull/9527) and [telegraf #9501](https://github.com/influxdata/telegraf/pull/9501) but didn't get a solution yet.

Example trouble we have:

in telegraf#9527 our solution was to kill pqos in telegraf rdt plugin golang code as such:
```
cmd := exec.Command("sudo", "killall", "-SIGINT", "pqos")
```
which introduces multiple issues:
- it will also kill any other pqos process in theory, although it's not likely we will run multiple pqos
- we will also need to add sudoer rule for telegraf to allow kill or killall cmd, which will allow it to kill any process
- we noticed we have to send `-SIGINT`  instead of default `-SIGTERM`, this is covered in #197 

Any advice from your team will be appreciated.
Thank you.

**Comment by kmabbasi** [comment]
You can create link of pqos for telegraph e.g. ln -s pqos pqos-telegraph

This way killing pqos-telegraph would only kill pqos processes that belong to telegraph

Thanks,
Khawar

**Comment by guoqiao** [comment]
@kmabbasi  We have discovered that the telegraf stop timeout issue was actually caused by a logging bug in its intel_rdt.go plugin: https://github.com/influxdata/telegraf/issues/9844

with that fixed, pqos can be closed by systemd without waiting.

thanks for the adivce, I will close this issue.
