### ISSUE TITLE
RDT Support for Core i9

### ISSUE THREAD

**Issue by lawrence-koh** [intel/intel-cmt-cat#199]
Hi, the `Hardware support` section of the README lists 11th gen Core i3, i5 and i7 processors, but not i9. 

Could I check if 10th and 11th-gen Core i9 processors are supported?

**Comment by kmabbasi** [comment]
Thanks Lawrence for the feedback.

Sure, you can check by adding processor branding string in [hw_cap_l3ca_brandstr](https://github.com/intel/intel-cmt-cat/blob/master/lib/hw_cap.c#L377). See this commit as an example https://github.com/intel/intel-cmt-cat/commit/78e1241f93bdbff2b3d6cb7c415882c642b686b7

Please let us know if you are successful and feel free to submit a pull request to enable your processor.

Regards,
Khawar

**Comment by kmabbasi** [comment]
It's been long time we didn't hear anything back from you. 
We are going to close this issue by considering it has been resolved.

Thanks,
Khawar
