### ISSUE TITLE
No module named 'pqos'

### ISSUE THREAD

**Issue by pklimowx** [intel/intel-cmt-cat#205]
After building appqos image in version v4.3.0 and using it in the container I see the following error:

```bash
Traceback (most recent call last):
  File "./appqos.py", line 47, in <module>
    import cache_ops
  File "/appqos_workspace/appqos/cache_ops.py", line 38, in <module>
    import caps
  File "/appqos_workspace/appqos/caps.py", line 37, in <module>
    import common
  File "/appqos_workspace/appqos/common.py", line 41, in <module>
    import pqos_api # pylint: disable=cyclic-import
  File "/appqos_workspace/appqos/pqos_api.py", line 41, in <module>
    from pqos import Pqos
ModuleNotFoundError: No module named 'pqos'
root@ar09-32-cyp:/opt/cek/intel-cmt-cat# 
```

I tried to follow [this](https://github.com/intel/intel-cmt-cat/wiki/FAQ#how-to-install-libpqos-python-wrapper), but without success. Currently, I'm using Ubuntu 21.04. But I saw the same error on RHEL 8.4 as well. The build process has no errors.

Any suggestions?

**Comment by shaorui1** [comment]
I had the same problem before, you can check the installation of pqos by running `pqos -V` from the command line. 
At this point, you may get an error showing some information like, `mount error`, which I solved with `docker -v /sys/fs/resctrl:/sys/fs/resctrl`. 
But there may be some new problems later, I raised the issue.

The wiki page of *resctrl* may help you. https://github.com/intel/intel-cmt-cat/wiki/resctrl

**Comment by pklimowx** [comment]
@shaorui1 try to run this command before you build the image: 

```bash
~/intel-cmt-cat# cp -r lib/python/pqos/ appqos/
```

it worked for me 😄

**Comment by kmabbasi** [comment]
Glad to hear that your issue has been resolved.

Thanks,
Khawar
