### ISSUE TITLE
cpuinfo_init() error -22

### ISSUE THREAD

**Issue by CQU-code-lover** [intel/intel-cmt-cat#206]
Hi,
Can you help me with this error :

> NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: cpuinfo_init() error -22
Error initializing PQoS library!

This is my cpuinfo:

> Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Platinum 8352S CPU @ 2.20GHz
Stepping:              6
CPU MHz:               2800.000
CPU max MHz:           3400.0000
CPU min MHz:           800.0000
BogoMIPS:              4400.00
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              49152K
NUMA node0 CPU(s):     0-15,64-79
NUMA node1 CPU(s):     16-31,80-95
NUMA node2 CPU(s):     32-47,96-111
NUMA node3 CPU(s):     48-63,112-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Thanks.

**Comment by mdcornu** [comment]
Can you post the command used to produce this error?
Also, please make sure you are running the command with root privilege's.

**Comment by CQU-code-lover** [comment]
Hi, 
This is the command:

> root@n138-025-201:~# pqos -d
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: cpuinfo_init() error -22
Error initializing PQoS library!

**Comment by mdcornu** [comment]
Could you provide the pqos library, OS and kernel version you are using please?

**Comment by mdcornu** [comment]
Also, the output from `pqos -Vs` and if you built the tools yourself, it may be helpful to rebuild with debugging info `make DEBUG=y`.

**Comment by CQU-code-lover** [comment]
Linux version 5.4.56.bsk.2-amd64
Debian 9

> root@n138-025-201:~# ls /usr/local/lib
libpqos.so  libpqos.so.4  libpqos.so.4.3.0

> root@n138-025-201:~# pqos -Vs
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
INFO: Requested interface: AUTO
INFO: resctrl not detected. Kernel version 4.10 or higher required
INFO: Selected interface: AUTO
INFO: CACHE: type 1, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 12 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 2, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 2, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 20 way(s), 1024 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 3, max id sharing this cache 128 (7 bits)
DEBUG: CACHE: not inclusive, complex cache indexing, 12 way(s), 65536 set(s), line size 64, 1 partition(s)
ERROR: cpuinfo_init() error -22
Error initializing PQoS library!

**Comment by aleksinx** [comment]
We have found issue with OS interface detection. In some cases library doesn't fallback to MSR interface.
```
INFO: Requested interface: AUTO
INFO: resctrl not detected. Kernel version 4.10 or higher required
INFO: Selected interface: AUTO
```
Selected interface is AUTO. You can force pqos to use MSR interface by adding --iface=msr parameter. Example
```pqos --iface=msr -d```

**Comment by CQU-code-lover** [comment]
Thanks for your reply, now everything works will.
