### ISSUE TITLE
Is it possible to use CMT inside SGX enclave?

### ISSUE THREAD

**Issue by AmbitionXiang** [intel/intel-cmt-cat#213]
If results of CMT can only be gotten through untrusted OS, enclaves cannot trust the results. Is it possible to directly get the results inside enclaves without involving OS?

**Comment by AmbitionXiang** [comment]
Thank you for your reply! I'm thinking about...maybe we can construct an oblivious memory by combining CMT and CAT if they are compatible with SGX.

**Comment by aleksinx** [comment]
No update for few months. Closing the issue now. Please reopen if you have more questions.
