### ISSUE TITLE
[Question] How can I run a specific program in a specific COS using both MSR and OS/Kernel interface?

### ISSUE THREAD

**Issue by kazi-m22** [intel/intel-cmt-cat#214]
Suppose I have a program named test.c and I want that to make sure that the program takes place only in COS1. How do I do that?

**Comment by aleksinx** [comment]
With MSR interface only core and be assigned to COS. You can pin selected cores to COS1 using command
```
pqos --iface=msr -a pqos -a llc:3=<CORES>
```
You can pin application to the selected core using `taskset`


With OS interface you can additionally assign PID to COS.

**Comment by theUnspecified** [comment]
In this link from intel [https://www.intel.com/content/www/us/en/developer/articles/technical/introduction-to-cache-allocation-technology.html](url) it says threads can also be placed in specific COS (thread, app, VM or containers).
Is this like binding thread to a core and set the core a special COS? Or is there any other way from kernel interface?

**Comment by aleksinx** [comment]
Yes, with OS interface PID can be assigned to COS using pqos -a pid:<COS>=<PID>

**Comment by aleksinx** [comment]
Closing the issue now. Please reopen if you have more questions.
