### ISSUE TITLE
Can I run pqos from terminal or C code without root permission?

### ISSUE THREAD

**Issue by kazi-m22** [intel/intel-cmt-cat#221]
I have tried running pqos from both terminal and C code. Even if I add prefix to install it somewhere else than default path, it asks for root permission each time. Is there any way to run it without root permission? If I do not use sudo, i get:

API lock initialization error!
Error initializing PQoS library!

**Comment by aleksinx** [comment]
No, root permissions are needed to access MSR register or resctrl filesystem.
