### ISSUE TITLE
ERROR: COS out of bounds for task <64957>

### ISSUE THREAD

**Issue by kazi-m22** [intel/intel-cmt-cat#222]
I am trying to switch the assigned COS for application based on PID using OS interface. When I try to assign COS number, it switches if the COS number is from 0-7. If I put any COS number grater than 7, it shows:

ERROR: COS out of bounds for task <64957>

From pqos -I -sV I have found following:
INFO: L3 CAT details: CDP support=1, CDP on=0, #COS=16, #ways=11, ways contention bit-mask 0x600

What I understand here, there should be 16 COS available

**Comment by mdcornu** [comment]
When using the OS interface, the number of COS is limited to what is common to all supported allocation technologies.
On your system, most likely MBA supports 8 COS, so L3CAT will be limited to 8 also.

See documentation here:
https://www.kernel.org/doc/html/latest/x86/resctrl.html
![image](https://user-images.githubusercontent.com/14837552/182802255-2d577fa4-4658-4cbd-b919-38a0229b703c.png)

**Comment by kazi-m22** [comment]
Thanks!
