### ISSUE TITLE
ERROR: os_cap_init() error 3

### ISSUE THREAD

**Issue by wdng** [intel/intel-cmt-cat#226]
model name      : Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
Linux version 5.15.0-1017-aws
OS: Ubuntu 22.04.1 LTS

```
sudo modprobe msr
sudo pqos -m llc:0
NOTE:  Mixed use of MSR and kernel interfaces to manage
            CAT or CMT & MBM may lead to unexpected behavior.
API lock initialization error!
Error initializing PQoS library!
```

Did I miss any steps before I use the pqos? Thanks!

**Comment by wdng** [comment]
Found the answer from the following link:
https://github.com/intel/intel-cmt-cat/wiki#enabling-intelr-rdt-support-in-the-linux-kernel

**Comment by IteratorandIterator** [comment]
Hello!
Could you tell me how you fixed this error?
Any reply will be appreciated!
