### ISSUE TITLE
Does this tool support for Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz?

### ISSUE THREAD

**Issue by RuifMaxx** [intel/intel-cmt-cat#239]
I have successfully installed `intel-cmt-cat-1.1.0` on ubuntu 18.04
However `pqos -e` and `pqos -a` look like do not work 
![image](https://user-images.githubusercontent.com/75245181/225196316-7bb874ee-aa61-40dd-b0bc-c5590e0a3cdb.png)

**Comment by RuifMaxx** [comment]
![image](https://user-images.githubusercontent.com/75245181/225196849-962c42b7-d415-44ed-b9c5-54f75dbb3d87.png)
the cpu usage is in this pic

**Comment by rkanagar** [comment]
Hi Ruif,

     Please refer pqos help for -e and -a options. pqos --help

Thanks,
Raghavan K.
