### ISSUE TITLE
Can pqos bind LLC and MB to PID?

### ISSUE THREAD

**Issue by yanxiaoqi932** [intel/intel-cmt-cat#242]
Can pqos bind LLC and MB to PID? Wiki only show how to bind LLC and MB to CPU cores.

**Comment by rkanagar** [comment]
Hi @yanxiaoqi932 ,
    Yes, it is possible. The wiki has that information. 
https://github.com/intel/intel-cmt-cat/wiki/Usage-Examples#14-pid-monitoring
