### ISSUE TITLE
Intel RDT for 13th Gen Intel(R) Core(TM) i9-13900KS

### ISSUE THREAD

**Issue by shubham4060** [intel/intel-cmt-cat#249]
Hi,

i was trying to configure l3cat on my 13th Gen intel i9 server. I couldnt find any resctrl file system available to mount. Further the linux config file has **CONFIG_X86_CPU_RESCTRL=y** in it but lscpu doesn't show any l3cat bit in the flags. below is the lscpu output

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
  BIOS Vendor ID:        Intel(R) Corporation
  Model name:            13th Gen Intel(R) Core(TM) i9-13900KS
    BIOS Model name:     13th Gen Intel(R) Core(TM) i9-13900KS To Be Filled By O.E.M. CPU @ 3.2GHz
    BIOS CPU family:     207
    CPU family:          6
    Model:               183
    Thread(s) per core:  1
    Core(s) per socket:  8
    Socket(s):           1
    Stepping:            1
    Frequency boost:     enabled
    CPU(s) scaling MHz:  151%
    CPU max MHz:         3201.0000
    CPU min MHz:         800.0000
    BogoMIPS:            6374.40
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clfl
                         ush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm con
                         stant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpui
                         d aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est
                         tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc
                         _deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fa
                         ult epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi fl
                         expriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invp
                         cid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1
                         xsaves avx_vnni dtherm ida arat pln pts umip pku ospke waitpkg gfni vaes vpc
                         lmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr
                          flush_l1d arch_capabilities
Virtualization features:
  Virtualization:        VT-x
Caches (sum of all):
  L1d:                   384 KiB (8 instances)
  L1i:                   256 KiB (8 instances)
  L2:                    16 MiB (8 instances)
  L3:                    36 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-7
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW seq
                         uence
  Srbds:                 Not affected
  Tsx async abort:       Not affected

but when i run **pqos --show --verbose**, it shows L3CA capability detected in the output, below is the output

NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
INFO: Requested interface: AUTO
INFO: resctrl not detected. Kernel version 4.10 or higher required
INFO: Selected interface: MSR
INFO: CACHE: type 1, level 1, max id sharing this cache 2 (1 bits)
INFO: CACHE: type 2, level 1, max id sharing this cache 2 (1 bits)
INFO: CACHE: type 3, level 2, max id sharing this cache 8 (3 bits)
INFO: CACHE: type 3, level 3, max id sharing this cache 128 (7 bits)
WARN: CPUID.0x7.0: Monitoring capability not supported!
INFO: Monitoring capability not detected
INFO: CPUID.0x7.0: L3 CAT not detected. Checking brand string...
WARN: Cache allocation not supported on model name '13th Gen Intel(R) Core(TM) i9-13900KS'!
ERROR: RDMSR failed for reg[0xca0] on lcore 0
INFO: L3CA capability detected
INFO: L3 CAT details: CDP support=0, CDP on=0, #COS=16, #ways=12, ways contention bit-mask 0x0
INFO: L3 CAT details: cache size 37748736 bytes, way size 3145728 bytes
INFO: CPUID.0x7.0: L2 CAT not supported
INFO: L2CA capability not detected
INFO: CPUID.0x7.0: MBA not supported
INFO: MBA capability not detected
L3CA COS definitions for Socket 0:
    L3CA COS0 => MASK 0xfff
    L3CA COS1 => MASK 0x212
    L3CA COS2 => MASK 0xeaa
    L3CA COS3 => MASK 0xeee
    L3CA COS4 => MASK 0xfff
    L3CA COS5 => MASK 0xfff
    L3CA COS6 => MASK 0xfff
    L3CA COS7 => MASK 0xfff
    L3CA COS8 => MASK 0xfff
    L3CA COS9 => MASK 0xfff
    L3CA COS10 => MASK 0xfff
    L3CA COS11 => MASK 0xfff
    L3CA COS12 => MASK 0xfff
    L3CA COS13 => MASK 0xfff
    L3CA COS14 => MASK 0xfff
    L3CA COS15 => MASK 0xfff
Core information for socket 0:
    Core 0, L2ID 0, L3ID 0 => COS0
    Core 1, L2ID 1, L3ID 0 => COS0
    Core 2, L2ID 2, L3ID 0 => COS0
    Core 3, L2ID 3, L3ID 0 => COS0
    Core 4, L2ID 4, L3ID 0 => COS0
    Core 5, L2ID 5, L3ID 0 => COS0
    Core 6, L2ID 6, L3ID 0 => COS0
    Core 7, L2ID 7, L3ID 0 => COS0
  
So can anyone please help as to whether l3cat is available on my machine or not as both the things specified above seems contradicting and thus confusing me to.

P.S : also added **rdt=cmt,l3cat** to boot options.

Thanks,

**Comment by rkanagar** [comment]
pqos -d
pqos -D
Above commands provide RDT capabilities of the system
