### ISSUE TITLE
The pqos tool fails on systems with 300 or more CPU cores

### ISSUE THREAD

**Issue by babumoger** [intel/intel-cmt-cat#261]
The pqos tool fails with the following errors on systems with 300 or more
CPU cores.
$pqos
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: Could not open /sys/fs/resctrl directory
ERROR: Failed to stop resctrl events
ERROR: Failed to start all selected OS monitoring events
Monitoring start error on core(s) 339, status 1

By default, the file descriptor limit is set to 1024 for a session. pqos
monitor uses 3 descriptors for each CPU for perf monitoring. So, it runs
out of limit(1024) on systems with 300 or more CPUs.

**Comment by rkanagar** [comment]
Fixed in v24.05
https://github.com/intel/intel-cmt-cat/releases/tag/v24.05
