### ISSUE TITLE
RDT support on Meteor Lake

### ISSUE THREAD

**Issue by KrisMichele** [intel/intel-cmt-cat#274]
I am just confirming the below is accurate, and I am not doing something wrong. I tried installing intel-cmt-cat with 185H, and I get the following:

OTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: CPUID.0x7.0: Monitoring capability not supported!
WARN: Cache allocation not supported on model name 'Intel(R) Core(TM) Ultra 9 185H'!
ERROR: No Platform QoS capability discovered
ERROR: discover_capabilities() error 1
Error initializing PQoS library!

Is there a plan to support Intel Core Ultra?

**Comment by rkanagar** [comment]
Hi @KrisMichele ,
       The Intel core Ultra 9185H is not supporting RDT. So the pqos tool is not running. Please find out RDT support in processor datasheet. Thanks.
