### ISSUE TITLE
 Enhance Intel PCM Integration with pqos for Comprehensive Memory Bandwidth Monitoring

### ISSUE THREAD

**Issue by bellalzohir** [intel/intel-cmt-cat#275]
I'm working to improve the monitoring capabilities of Intel's Platform Quality of Service (PQoS) when used alongside Intel Performance Counter Monitor (PCM). I've encountered a limitation that seems to affect the ability to monitor memory bandwidth effectively.

Environment:

OS: Linux kernel 5.15.0-112-generic
Hardware: Capable of memory bandwidth monitoring
Configuration: Enabled RDT features (rdt=cmt, mbmtotal, mbmlocal, l3cat, l3cdp, l2cat, l2cdp, mba) through GRUB with GRUB_CMDLINE_LINUX="hugepagesz=1G hugepages=12 rdt=cmt, mbmtotal, mbmlocal, l3cat, l3cdp, l2cat, l2cdp, mba"
Issue:
Using the default pqos command, the monitoring is limited to Last Level Cache (LLC) but does not include memory bandwidth. However, when I switch to pqos-msr, I can successfully collect the bandwidth metrics. I suspect the issue arises when using Intel PCM, which defaults to using the standard pqos that only captures LLC metrics, missing out on the bandwidth details even though my hardware supports it.

Expected Behavior:
Intel PCM should be capable of utilizing the full monitoring capabilities of pqos, including memory bandwidth metrics, when the hardware and OS configurations support it.

Actual Behavior:
Only LLC metrics are monitored, not memory bandwidth, when using Intel PCM with the default pqos setup.

Steps to Reproduce:

Include the necessary RDT options in the GRUB configuration and rebuild the grub with the updated settings.
Check the Linux kernel configuration for `CONFIG_X86_CPU_RESCTRL=y.`
Execute sudo pqos -d and monitoring is  limited to LLC metrics.

```
sudo pqos -d
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
OS capabilities (Linux kernel 5.15.0-112-generic)
    Monitoring
        Cache Monitoring Technology (CMT) events:
            LLC Occupancy (LLC)
                 I/O RDT: unsupported
        PMU events:
            LLC misses
            LLC references
            Instructions/Clock (IPC)
    Allocation
        Memory Bandwidth Allocation (MBA)
            Num COS: 8
            CTRL: unsupported
```
The RESCTRL is mounted 
/sys/fs/resctrl
├── COS1
│   ├── cpus
│   ├── cpus_list
│   ├── mode
│   ├── mon_data
│   │   ├── mon_L3_00
│   │   │   └── llc_occupancy
│   │   └── mon_L3_01
│   │       └── llc_occupancy
│   ├── mon_groups
│   ├── schemata
│   ├── size
│   └── tasks

Execute sudo pqos-msr -d and note the additional memory bandwidth metrics being monitored.

```
sudo pqos-msr -d
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: resctl filesystem mounted! Using MSR interface may corrupt resctrl filesystem and cause unexpected behaviour
Hardware capabilities
    Monitoring
        Cache Monitoring Technology (CMT) events:
            LLC Occupancy (LLC)
                 I/O RDT: unsupported
        Memory Bandwidth Monitoring (MBM) events:
            Total Memory Bandwidth (TMEM)
                 I/O RDT: unsupported
            Local Memory Bandwidth (LMEM)
                 I/O RDT: unsupported
            Remote Memory Bandwidth (RMEM) (calculated)
                 I/O RDT: unsupported
        PMU events:
            Instructions/Clock (IPC)
            LLC misses
            LLC references
            LLC misses - pcie read
            LLC misses - pcie write
            LLC references - pcie read
            LLC references - pcie write
    Allocation
        Cache Allocation Technology (CAT)
            L3 CAT
                CDP: disabled
                Non-Contiguous CBM: unsupported
                I/O RDT: unsupported
                Num COS: 16
        Memory Bandwidth Allocation (MBA)
            Num COS: 8
```

Potential Solution:
Could there be an enhancement or a configuration guideline that ensures Intel PCM leverages pqos-msr or a similar setup to monitor both LLC and memory bandwidth effectively?

Thank you for looking into this issue. I am looking forward to your insights and am willing to assist with further testing or information if needed.

**Comment by rkanagar** [comment]
Hi @bellalzohir 
    The Intel PCM and pqos are seperate projects. The default interface in pqos is OS. That is resctrl sysfs. Please provide output of the error. What pqos version are you using?. If you just type "pqos or pqos --iface=os", that provides llc, MBL and MBR output.

https://github.com/intel/pcm
