### ISSUE TITLE
Expected MBA controller but not requested while configuring MBA in %

### ISSUE THREAD

**Issue by QiongwenXu** [intel/intel-cmt-cat#276]
Hi, I am using MBA to limit memory bandwidth of COS1. However, I was unable to configure MBA in % (I succeeded in configuring it in MB/s). The following is the commands and outputs. Could you please help me? Thanks!

$ sudo pqos -e 'mba_max:1=20000'
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
SOCKET 0 MBA COS1 => 20000 MBps
SOCKET 1 MBA COS1 => 20000 MBps
Allocation configuration altered.
$ sudo pqos -I -e 'mba:1=100'
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: Expected MBA controller but not requested!
SOCKET 0 MBA COS1 - FAILED!
Allocation configuration error!
$ sudo pqos -e 'mba:1=100'
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: Expected MBA controller but not requested!
SOCKET 0 MBA COS1 - FAILED!
Allocation configuration error!

other information:
**intel-cmt-cat commit**: ce819d5fedc91fae1f148f91ed29e5d37d322060
**$ sudo pqos -d**
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
OS capabilities (Linux kernel 5.4.0-182-generic)
    Monitoring
        Cache Monitoring Technology (CMT) events:
            LLC Occupancy (LLC)
                 I/O RDT: unsupported
        Memory Bandwidth Monitoring (MBM) events:
            Local Memory Bandwidth (LMEM)
                 I/O RDT: unsupported
            Total Memory Bandwidth (TMEM)
                 I/O RDT: unsupported
            Remote Memory Bandwidth (RMEM) (calculated)
                 I/O RDT: unsupported
        PMU events:
            LLC misses
            LLC references
            Instructions/Clock (IPC)
    Allocation
        Memory Bandwidth Allocation (MBA)
            Num COS: 8
            CTRL: enabled

**kernel:** 5.4.0-182-generic
**os version: $ lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
**$ lscpu**
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             64
On-line CPU(s) list:                0-63
Thread(s) per core:                 2
Core(s) per socket:                 16
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz
Stepping:                           7
CPU MHz:                            980.795
CPU max MHz:                        3200.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4200.00
Virtualization:                     VT-x
L1d cache:                          1 MiB
L1i cache:                          1 MiB
L2 cache:                           32 MiB
L3 cache:                           44 MiB
NUMA node0 CPU(s):                  0-15,32-47
NUMA node1 CPU(s):                  16-31,48-63
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        KVM: Mitigation: Split huge pages
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
                                     and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer
                                     sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB fillin
                                    g, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Mitigation; TSX disabled
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mc
                                    a cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss 
                                    ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art
                                     arch_perfmon pebs bts rep_good nopl xtopology nonstop_
                                    tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cp
                                    l vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dc
                                    a sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer 
                                    aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpu
                                    id_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ss
                                    bd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi fl
                                    expriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx
                                    2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq
                                     rdseed adx smap clflushopt clwb intel_pt avx512cd avx5
                                    12bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cq
                                    m_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat
                                     pln pts hwp hwp_act_window hwp_pkg_req pku ospke avx51
                                    2_vnni md_clear flush_l1d arch_capabilities

**Comment by rkanagar** [comment]
Hi @QiongwenXu ,
     100% allocation of memory bandwidth is not allowed to any core. The maximum is 90% per-core. Thanks.
