### ISSUE TITLE
Question about the CAT support on Celeron N3350

### ISSUE THREAD

**Issue by PennPanda** [intel/intel-cmt-cat#50]
Hi,

Does the Intel Celeron N3350 (based on the Apollo Lake platform) have the Intel CAT technology?
How many CLOS registers do the processor support?
How many bits in the CBM field in the CLOS registers on the processor?

I'm sorry for bothering you about the details. 
I couldn't find the information anywhere else.
I want to make sure the Intel SoC I will buy does have the necessary functionalities of Intel CAT.

Thanks,

Meng

**Comment by vCloudernBeer** [comment]
I am no expert on this but the README file stated only Xeon and Atom processor:

Hardware Support
================

Table 1. Intel(R) RDT hardware support
+-----------------------------------------------------------------------------------+
|                                            | CMT | MBM | L3 CAT | L3 CDP | L2 CAT |
|--------------------------------------------+-----+-----+--------+--------+--------|
|Intel(R) Xeon(R) processor E5 v3            | Yes | No  | Yes (1)| No     | No     |
|--------------------------------------------+-----+-----+--------+--------+--------|
|Intel(R) Xeon(R) processor D                | Yes | Yes | Yes (2)| No     | No     |
|--------------------------------------------+-----+-----+--------+--------+--------|
|Intel(R) Xeon(R) processor E3 v4            | No  | No  | Yes (3)| No     | No     |
|--------------------------------------------+-----+-----+--------+--------+--------|
|Intel(R) Xeon(R) processor E5 v4            | Yes | Yes | Yes (2)| Yes    | No     |
|--------------------------------------------+-----+-----+--------+--------+--------|
|Intel(R) Atom(R) processor for Server C3000 | No  | No  | No     | No     | Yes (4)|
+-----------------------------------------------------------------------------------+

**Comment by mdcornu** [comment]
This table contains a list of CPU's that we have used to test our software. This may not be a complete list of all supporting CPU's.

Regards,
Marcel

**Comment by taget** [comment]
Seems not , see https://www.intel.com/content/www/us/en/architecture-and-technology/resource-director-technology.html
 Intel® RDT is a key feature set to optimize application performance and enhance the capabilities of orchestration and virtualization management server systems using **Intel® Xeon® processors.**

**Comment by tkanteck** [comment]
taget, could you please clarify what do you mean by "seems not" in your comment?
Thanks,
Tomasz

**Comment by taget** [comment]
@tkanteck Tomasz,
sorry if I bring confusing,  Intel Celeron N3350 `seems not` support Intel RDT according https://www.intel.com/content/www/us/en/architecture-and-technology/resource-director-technology.html, as Intel Celeron N3350 is not a member of [Intel® Xeon® processors](https://www.intel.com/content/www/us/en/servers/server-products.html)

**Comment by tkanteck** [comment]
In order to check if Intel(R) RDT is supported (and to what scope) on certain processor model I would advise to look into the product specification and not general description of the technology.
Running 'pqos' tool to enumerate hardware capabilities on certain processor model is also very practical solution.

**Comment by mdcornu** [comment]
Closing this issue. Please reopen if needed.

Regards,
Marcel
