### ISSUE TITLE
lib/Makefile calls ldconfig. it must not

### ISSUE THREAD

**Issue by fenrus75** [intel/intel-cmt-cat#53]
ldconfig is a root-only operation, and distros and users alike do not and should not build things as root.... there is a reason no other package uses ldconfig as part of its makefiles

(and please consider using autoconf or the like. yes autoconfig is evil, but speaking as a distro creator, the Makefiles in this project are much worse than autoconf)

**Comment by tkanteck** [comment]
Thanks for the contact and the feedback. This is true that 'ldoconfig' is called by lib/Makefile but as part of install target only. Consequently it is not required to be root for library compilation and any user should be able to do it.
We are open to suggestions and pull requests with regard to improvements in the existing build system. We'll also have a look into evil autoconf :)

**Comment by fenrus75** [comment]
https://github.com/clearlinux-pkgs/intel-cmt-cat/blob/master/build.patch

this is the kind of thing linux distros need to do for their packaging; even make install into a chroot-like directory (with DESTDIR) will be done as non-root.

intel-cmt-cat is pretty much the only package in the whole distro that runs ldconfig as part of "make install".... it's at least highly unusual

**Comment by tkanteck** [comment]
How does clearlinux intel-cmt-cat spec file look like? 'make install' is not part of Fedora spec file for instance and so no patching is required.

**Comment by fenrus75** [comment]
https://github.com/clearlinux-pkgs/intel-cmt-cat/blob/master/intel-cmt-cat.spec

Fedora hates your make install so much that they decided to open code it instead, and put a nasty comment instead... I wouldn't take Fedora's workaround as a sign that the Makefile is doing the right thing ;-)

(from their spec)

# Not doing make install as it strips the symbols.
# Using files from the build directory.

**Comment by tkanteck** [comment]
Thank you but actually we wrote this spec file file so we cannot really hate ourselves.

We'll consider removing ldconfig from the lib/Makefile or creating separate target for packaging.
The only reason 'ldocnfig' is there is for users installing software from a tarball.

**Comment by fenrus75** [comment]
fwiw Debian seems to have a patch very similar

http://http.debian.net/debian/pool/main/i/intel-cmt-cat/intel-cmt-cat_1.0.1-1.debian.tar.xz

as does opensuse

https://build.opensuse.org/package/view_file/server:monitoring/intel-cmt-cat/fix-ldconfig-call.patch?expand=1

**Comment by mdcornu** [comment]
Closing this issue. Please reopen if needed.

Regards,
Marcel
