### ISSUE TITLE
Switching task execution while monitoring

### ISSUE THREAD

**Issue by narru19** [intel/intel-cmt-cat#64]
Hi!
I'm conducting an experiment where I use monitoring on a per thread basis to monitor task events. The way I'm trying to achieve it is by:
- When a task starts execution, the thread executing it starts monitoring for PQoS events through **pqos_mon_start_pid**.
- When a task stops for whatever reason (i.e. blocked but not finished) the thread accumulates its events (**pqos_mon_poll**) into the task. 
- When a task that was blocked restarts its execution, the thread resumes monitoring through **pqos_mon_start_pid**.

I am getting various errors due to starting monitoring more than once in a thread. I assumed I would be able to do it this way in order to restart data structures, as **pqos_mon_stop** frees them. Are there any functions that allow resetting the monitoring of threads (events) without destroying data structures? I'm basically looking for a "start-pause-resume-stop" pattern.

Thanks in advance,

Toni

**Comment by mdcornu** [comment]
Hi Toni,

I'm not sure I fully understand the scenario. Can you clarify the difference between a task and a thread in your explanation? 

There is no function to pause and resume monitoring. However, when monitoring, only MBM counters will be accumulating while the task is blocked (LLC occupancy is reported as a snapshot at that moment in time).  Perhaps you could achieve "resume" like functionality by simply polling once the task restarts execution? This would act as a new starting point for future calls to **pqos_mon_poll** to calculate delta values.

Regards,
Marcel

**Comment by narru19** [comment]
Hi Marcel,

By thread I meant a unit similar to a pthread, as for task it would basically be some application ran on one of these threads, so I'd basically want to know events per-task. Thus, to avoid events collected from other tasks ran by the same thread I wanted some kind of pause-resume functionality.

However, what you mentioned seems more appropriate, I'll just take these snapshots of values and compare them to calculate delta values.

Thanks for the quick response!

Regards,
Toni
