### ISSUE TITLE
lib/resctrl_monitoring.c - line 163, column 9 Undefined or garbage value returned to caller

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-cmt-cat#68]
Building intel-cmt-cat (from current tip) with clang 6.0, (scan-build), there is an issue where variable ret is potentially uninitialized and garbage is being returned from function resctrl_mon_init.

This can potentially occur when istat(RESCTRL_PATH_INFO, &st) is non-zero, hence ret is not set.  I think the correct fix is to initialize ret to zero when it is declared, but I'm not 100% sure.

**Comment by aleksinx** [comment]
Thank you for message. We are aware of this issue. We already prepared patch that includes fix for this issue but it is not merged to master yet.

**Comment by aleksinx** [comment]
The fix for this issue was finally merged into master.

Regards
Michał

**Comment by mdcornu** [comment]
Closing this issue. Please reopen if needed.

Regards,
Marcel
