### ISSUE TITLE
[Question] About the compatibility between CAT and cgroups

### ISSUE THREAD

**Issue by Pacific73** [intel/intel-cmt-cat#70]
Hi,

I'm a senior undergrad and want to write a software suite to implement **the isolation mechanism of shared resources** as my graduation thesis/project.

I want to use **cgroups (cpuset subsystem)** to assign physical cores to different tasks, while using **CAT** to assign LLC spaces to different tasks. Also, I want to use **MEM** to monitor the memory BW overall usage.

But it does not seem to be feasible when I see Table 3/4 in README. **Table 3 says cgroups is not compatible with CAT (L3 CAT) / MBM and table 4 says it is depend on Linux perf enabling.** Does that mean I can't implement this functionality in my userspace program?

But in paper [Heracles: Improving Resource Efficiency at Scale](http://csl.stanford.edu/~christos/publications/2015.heracles.isca.pdf) by Stanford Univ. and Google, they implemented this system using **cpuset** and **CAT** tech at the same time (page 5, rightdown corner, you'll see core isolation and llc isolation part). I'm confused.

Hope you can help me solve this problem.
Thanks!

Chenyu Zhang
2018/4/9

**Comment by mdcornu** [comment]
Hi Chenyu,

[Table 3. OS interface feature support](https://github.com/intel/intel-cmt-cat/blob/8a1dc4f326aa82c162fd46430001e25b2587aff3/README#L222) in the README describes when Intel(R) RDT features were enabled in the Linux kernel. 

According to this table, once you are using a kernel v4.10 or later, there should be no issue using CAT/MBM to allocate & monitor resources for a task using the intel-cmt-cat library. The library will leverage the Resctrl (for CAT) and Perf (for MBM) kernel frameworks to do this.

The Linux cgroups mentioned in the Software interoperability table refers to a legacy out of tree patch to enable CAT through cgroups. This is not part of the mainline kernel so won't affect your application.

To allow allocation and monitoring on a per task basis using the intel-cmt-cat library, simply set the [interface](https://github.com/intel/intel-cmt-cat/blob/8a1dc4f326aa82c162fd46430001e25b2587aff3/lib/pqos.h#L133) flag to PQOS_INTER_OS when initializing the library. 
Or refer to[ OS interface usage examples](https://github.com/intel/intel-cmt-cat/wiki/Usage-Examples#14-using-the-oskernel-interface-v10) if using the pqos command line utility.

Regards,
Marcel

**Comment by Pacific73** [comment]
Oh I got it. Thanks for your reply in time!
