### ISSUE TITLE
Is there going to be processors that support both CAT and SGX?

### ISSUE THREAD

**Issue by c-gongye** [intel/intel-cmt-cat#71]
Hi,

Could you please tell me will there be processors that support both CAT and SGX?

Or do some of these [Xeon processors that support SGX](https://ark.intel.com/Search/FeatureFilter?productType=processors&SoftwareGuardExtensions=true&FamilyText=Intel%C2%AE%20Xeon%C2%AE%20Processors) also support CAT and just are not tested?

Thanks!

**Comment by tkanteck** [comment]
Hi,
Unfortunately, ARK doesn't show Intel(R) RDT on the list of processor features as of yet. 
Are looking for specific Intel(R) Xeon(R) model? If so then we might be able to help.
Thanks,
Tomasz

**Comment by c-gongye** [comment]
Hi Tomasz,
Thank you for the response!
I am looking for these models:
- Intel® Xeon® Processor E3-1268L v5
- Intel® Xeon® Processor E3-1285 v6
- Intel® Xeon® Processor E3-1280 v6

Could you please provide the RDT hardware support table for these processors? Thanks in advance.

**Comment by tkanteck** [comment]
Thanks! Let me check Intel(R) RDT support status on these processor models.

We aim to keep this table up to date https://github.com/intel/intel-cmt-cat/blob/master/README#L112 but it is missing information about models of your interest,

**Comment by tkanteck** [comment]
None of the 3 processor models that you listed seem to support Intel(R) RDT. You may need to look into Intel(R) Xeon(R) D, Intel(R) Xeon(R) E5/E7 or Intel(R) Xeon(R) Scalable Processors.
If you have a new shortlist feel free to send it here to double check Intel(R) RDT availability.

**Comment by c-gongye** [comment]
Now I am checking these processors:
- Intel® Xeon® Processor E3-1505L v5
- Intel Atom® Processor C3558
- Intel® Xeon® Processor E3-1505L v6
- Intel® Xeon® Bronze 3104
- Intel® Xeon® Silver 4112

Hopefully, the RDT info will soon be available on ARK :) Thanks in advance!

**Comment by mdcornu** [comment]
Closing this issue for now. Sorry we couldn't be more help here.
Please reopen if needed.

Regards,
Marcel

**Comment by donnod** [comment]
Hi, is there any update here? I am also looking for processors that support both CAT and SGX.
