### ISSUE TITLE
Question about setting COS for threads

### ISSUE THREAD

**Issue by Jeongseob** [intel/intel-cmt-cat#72]
Hi,

I would like to use cache separately between two threads of my application so that I could write code setting COS for each thread differently while initializing the threads. Here, I am concerned about that the underlying OS can migrate the application threads from one to another core. It results in that I may need to set the COS on that core again, but it would be difficult to get the notification from OS to applications for every thread migrations. 

Except for pinning threads to specific cores, how can I ensure that the threads are running with the corresponding COS?

Thanks,
Jeongseob

**Comment by mdcornu** [comment]
Hi Jeongseob,

I will close this issue if there is nothing else to do here.
Feel free to reopen if needed.

Regards,
Marcel
