### ISSUE TITLE
pqos -I has errors

### ISSUE THREAD

**Issue by fzhedu** [intel/intel-cmt-cat#73]
_The errors are listed below:_
[claims@ds123 pqos]$ sudo ./pqos -I
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
**ERROR: OS interface selected but not supported
ERROR: discover_os_capabilities() error 1**
Error initializing PQoS library!

_Besides, the Monitoring is not included in OS capabilities. Is this related to the preceding errors?_
[claims@ds123 pqos]$ sudo ./pqos -d
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Hardware capabilities
    Monitoring
        Cache Monitoring Technology (CMT) events:
            LLC Occupancy (LLC)
        Memory Bandwidth Monitoring (MBM) events:
            Total Memory Bandwidth (TMEM)
            Local Memory Bandwidth (LMEM)
            Remote Memory Bandwidth (RMEM) (calculated)
        PMU events:
            Instructions/Clock (IPC)
            LLC misses
    Allocation
        Cache Allocation Technology (CAT)
            L3 CAT
                CDP: enabled
                Num COS: 8
        Memory Bandwidth Allocation (MBA)
            Num COS: 8
OS capabilities (Linux kernel 4.16.11-1.el7.elrepo.x86_64)
    Allocation
        Cache Allocation Technology (CAT)
            L3 CAT
                CDP: enabled
                Num COS: 8
        Memory Bandwidth Allocation (MBA)
            Num COS: 8

_The version of my OS is 4.16.11-1.el7.elrepo.x86_64, which is upgraded by "yum"._

**Comment by mdcornu** [comment]
Hi fzhedu,

As mentioned in our [README](https://github.com/intel/intel-cmt-cat/blob/33a583d85076f488d528cc4b906e8eece4e370b3/README#L159), please find errata for Intel(R) Xeon(R) Processor Scalable Family [here](https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/xeon-scalable-spec-update.pdf?asset=14615).

Due to these errata, some OS features may be disabled by default.
Please see instructions on how to enable/disable individual features in the kernel on our [wiki](https://github.com/intel/intel-cmt-cat/wiki#enabling-intelr-rdt-support-in-the-linux-kernel).

Can you please check the "flags" string the in /proc/cpuinfo file for the following events:
`cqm_occup_llc cqm_mbm_total cqm_mbm_local`

If not present, then these monitoring events may have to be manually enabled.

Regards,
Marcel

**Comment by fzhedu** [comment]
Hi Marcel,
Thanks for your replying!
According to your answer, I recompiled my kernel with turning on the RDT processor feature.
Now, The OS capabilities include Monitoring.

However, a new problem occurs:
[claims@ds123 pqos]$ sudo ./pqos -I -p
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Monitoring top-pids enabled
**ERROR: Failed to start all selected OS monitoring events
PID 25729 monitoring start error,status 1**

My CPU: Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz "Intel(r) microarchitecture codename Skylake-
SP"

Regards,
Zhuhe Fang

**Comment by mdcornu** [comment]
Hi fzhedu,

Apologies for the delayed response. I seem to have missed your reply.

This command will discover the top 10 CPU utilizing PID's and begin monitoring them.
In your case, I believe you hit a corner case where PID 25729 was selected to be monitored but died before monitoring began, causing the API to return an error.

Can you please retry this command with the latest code please?

Regards,
Marcel

**Comment by fzhedu** [comment]
Hi Marcel,

Thanks for your replying.
I try the latest code, the errors still occur.

**sudo ./pqos -I -p**
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Monitoring top-pids enabled
ERROR: Failed to start all selected OS monitoring events
PID 2829 monitoring start error,status 1
The selected PID 2829 is always active, which is not the corner case.

**sudo ./pqos -I** 
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
_WARN: As of Kernel 4.10, Intel(R) RDT perf results per core are found to be incorrect._
ERROR: Failed to start all selected OS monitoring events
Monitoring start error on core(s) 0, status 1

Is the error resulted from the _WARN_?

Regards,
Zhuhe Fang

**Comment by mdcornu** [comment]
Hi Zhuhe,

My suspicion is this could be related to your kernel version.
We generally test with the mainline kernel. It looks like you're using a patched RHEL/CentOS version of the mainline kernel which may behave slightly different.

Can you please try 2 things:
1. Rebuild the library and utility with debugging info enabled and try again:
`make clean && make DEBUG=y`
`sudo LD_LIBRARY_PATH=./lib ./pqos/pqos -I -p`
2. Send the output of the following command:
`sudo LD_LIBRARY_PATH=./lib ./pqos/pqos -s -V`

You could also try another kernel version but this can be some work so I understand if you skip this option.

If these don't help in root causing the issue, then I will investigate the issue further as soon as I can.

Regards,
Marcel

**Comment by fzhedu** [comment]
Hi Marcel,
Thanks for your replying. The output is shown as follows. 
I tried on another server with the same kernel, but its micro architecture is Haswell, this issue does not occur. This issue does not limit me to use CAT. If you are interest in this issue, you can investigate it. If not, you can ignore it temporarily.

`sudo LD_LIBRARY_PATH=./lib ./pqos/pqos -I -p`
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Monitoring top-pids enabled
ERROR: Failed to start all selected OS monitoring events
pqos: monitor.c:835: monitor_setup: Assertion `ret == 0' failed.
Aborted

`sudo LD_LIBRARY_PATH=./lib ./pqos/pqos -s -V`
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
INFO: CACHE: type 1, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 2, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 2, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 16 way(s), 1024 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 3, max id sharing this cache 16 (4 bits)
DEBUG: CACHE: not inclusive, complex cache indexing, 11 way(s), 16384 set(s), line size 64, 1 partition(s)
DEBUG: Detected core 0, socket 0, L2 ID 0, L3 ID 0, APICID 0
DEBUG: Detected core 1, socket 1, L2 ID 8, L3 ID 1, APICID 16
DEBUG: Detected core 2, socket 0, L2 ID 7, L3 ID 0, APICID 14
DEBUG: Detected core 3, socket 1, L2 ID 15, L3 ID 1, APICID 30
DEBUG: Detected core 4, socket 0, L2 ID 1, L3 ID 0, APICID 2
DEBUG: Detected core 5, socket 1, L2 ID 9, L3 ID 1, APICID 18
DEBUG: Detected core 6, socket 0, L2 ID 6, L3 ID 0, APICID 12
DEBUG: Detected core 7, socket 1, L2 ID 14, L3 ID 1, APICID 28
DEBUG: Detected core 8, socket 0, L2 ID 2, L3 ID 0, APICID 4
DEBUG: Detected core 9, socket 1, L2 ID 10, L3 ID 1, APICID 20
DEBUG: Detected core 10, socket 0, L2 ID 5, L3 ID 0, APICID 10
DEBUG: Detected core 11, socket 1, L2 ID 13, L3 ID 1, APICID 26
DEBUG: Detected core 12, socket 0, L2 ID 3, L3 ID 0, APICID 6
DEBUG: Detected core 13, socket 1, L2 ID 11, L3 ID 1, APICID 22
DEBUG: Detected core 14, socket 0, L2 ID 4, L3 ID 0, APICID 8
DEBUG: Detected core 15, socket 1, L2 ID 12, L3 ID 1, APICID 24
DEBUG: Detected core 16, socket 0, L2 ID 0, L3 ID 0, APICID 1
DEBUG: Detected core 17, socket 1, L2 ID 8, L3 ID 1, APICID 17
DEBUG: Detected core 18, socket 0, L2 ID 7, L3 ID 0, APICID 15
DEBUG: Detected core 19, socket 1, L2 ID 15, L3 ID 1, APICID 31
DEBUG: Detected core 20, socket 0, L2 ID 1, L3 ID 0, APICID 3
DEBUG: Detected core 21, socket 1, L2 ID 9, L3 ID 1, APICID 19
DEBUG: Detected core 22, socket 0, L2 ID 6, L3 ID 0, APICID 13
DEBUG: Detected core 23, socket 1, L2 ID 14, L3 ID 1, APICID 29
DEBUG: Detected core 24, socket 0, L2 ID 2, L3 ID 0, APICID 5
DEBUG: Detected core 25, socket 1, L2 ID 10, L3 ID 1, APICID 21
DEBUG: Detected core 26, socket 0, L2 ID 5, L3 ID 0, APICID 11
DEBUG: Detected core 27, socket 1, L2 ID 13, L3 ID 1, APICID 27
DEBUG: Detected core 28, socket 0, L2 ID 3, L3 ID 0, APICID 7
DEBUG: Detected core 29, socket 1, L2 ID 11, L3 ID 1, APICID 23
DEBUG: Detected core 30, socket 0, L2 ID 4, L3 ID 0, APICID 9
DEBUG: Detected core 31, socket 1, L2 ID 12, L3 ID 1, APICID 25
DEBUG: Adding monitoring event: resource ID 1, type 1 to table index 0
DEBUG: Adding monitoring event: resource ID 1, type 4 to table index 1
DEBUG: Adding monitoring event: resource ID 1, type 2 to table index 2
DEBUG: Adding monitoring event: resource ID 1, type 8 to table index 3
DEBUG: Adding monitoring event: resource ID 0, type 32768 to table index 4
DEBUG: Adding monitoring event: resource ID 0, type 16384 to table index 5
INFO: Monitoring capability detected
INFO: CPUID.0x7.0: L3 CAT supported
INFO: L3 CDP is disabled
INFO: L3 CAT details: CDP support=1, CDP on=0, #COS=16, #ways=11, ways contention bit-mask 0x600
INFO: L3 CAT details: cache size 11534336 bytes, way size 1048576 bytes
INFO: L3CA capability detected
INFO: CPUID 0x10.0: L2 CAT not supported!
INFO: L2CA capability not detected
INFO: MBA details: #COS=8, linear, max=90, step=10
INFO: MBA capability detected
INFO: resctrl detected
INFO: OS support for CMT detected
INFO: OS support for L3 CAT detected
INFO: OS support for MBA detected
WARN: resctl filesystem mounted! Using MSR interface may corrupt resctrl filesystem and cause unexpected behaviour
DEBUG: allocation init OK
DEBUG: Max RMID per monitoring cluster is 64
DEBUG: monitoring init OK
L3CA/MBA COS definitions for Socket 0:
    L3CA COS0 => MASK 0x7ff
    L3CA COS1 => MASK 0x7ff
    L3CA COS2 => MASK 0x7ff
    L3CA COS3 => MASK 0x7ff
    L3CA COS4 => MASK 0x7ff
    L3CA COS5 => MASK 0x7ff
    L3CA COS6 => MASK 0x7ff
    L3CA COS7 => MASK 0x7ff
    L3CA COS8 => MASK 0x7ff
    L3CA COS9 => MASK 0x7ff
    L3CA COS10 => MASK 0x7ff
    L3CA COS11 => MASK 0x7ff
    L3CA COS12 => MASK 0x7ff
    L3CA COS13 => MASK 0x7ff
    L3CA COS14 => MASK 0x7ff
    L3CA COS15 => MASK 0x7ff
    MBA COS0 => 100% available
    MBA COS1 => 100% available
    MBA COS2 => 100% available
    MBA COS3 => 100% available
    MBA COS4 => 100% available
    MBA COS5 => 100% available
    MBA COS6 => 100% available
    MBA COS7 => 100% available
L3CA/MBA COS definitions for Socket 1:
    L3CA COS0 => MASK 0x7ff
    L3CA COS1 => MASK 0x7ff
    L3CA COS2 => MASK 0x7ff
    L3CA COS3 => MASK 0x7ff
    L3CA COS4 => MASK 0x7ff
    L3CA COS5 => MASK 0x7ff
    L3CA COS6 => MASK 0x7ff
    L3CA COS7 => MASK 0x7ff
    L3CA COS8 => MASK 0x7ff
    L3CA COS9 => MASK 0x7ff
    L3CA COS10 => MASK 0x7ff
    L3CA COS11 => MASK 0x7ff
    L3CA COS12 => MASK 0x7ff
    L3CA COS13 => MASK 0x7ff
    L3CA COS14 => MASK 0x7ff
    L3CA COS15 => MASK 0x7ff
    MBA COS0 => 100% available
    MBA COS1 => 100% available
    MBA COS2 => 100% available
    MBA COS3 => 100% available
    MBA COS4 => 100% available
    MBA COS5 => 100% available
    MBA COS6 => 100% available
    MBA COS7 => 100% available
Core information for socket 0:
    Core 0, L2ID 0, L3ID 0 => COS0, RMID0
    Core 2, L2ID 7, L3ID 0 => COS0, RMID0
    Core 4, L2ID 1, L3ID 0 => COS0, RMID0
    Core 6, L2ID 6, L3ID 0 => COS0, RMID0
    Core 8, L2ID 2, L3ID 0 => COS0, RMID0
    Core 10, L2ID 5, L3ID 0 => COS0, RMID0
    Core 12, L2ID 3, L3ID 0 => COS0, RMID0
    Core 14, L2ID 4, L3ID 0 => COS0, RMID0
    Core 16, L2ID 0, L3ID 0 => COS0, RMID0
    Core 18, L2ID 7, L3ID 0 => COS0, RMID0
    Core 20, L2ID 1, L3ID 0 => COS0, RMID0
    Core 22, L2ID 6, L3ID 0 => COS0, RMID0
    Core 24, L2ID 2, L3ID 0 => COS0, RMID0
    Core 26, L2ID 5, L3ID 0 => COS0, RMID0
    Core 28, L2ID 3, L3ID 0 => COS0, RMID0
    Core 30, L2ID 4, L3ID 0 => COS0, RMID0
Core information for socket 1:
    Core 1, L2ID 8, L3ID 1 => COS0, RMID0
    Core 3, L2ID 15, L3ID 1 => COS0, RMID0
    Core 5, L2ID 9, L3ID 1 => COS0, RMID0
    Core 7, L2ID 14, L3ID 1 => COS0, RMID0
    Core 9, L2ID 10, L3ID 1 => COS0, RMID0
    Core 11, L2ID 13, L3ID 1 => COS0, RMID0
    Core 13, L2ID 11, L3ID 1 => COS0, RMID0
    Core 15, L2ID 12, L3ID 1 => COS0, RMID0
    Core 17, L2ID 8, L3ID 1 => COS0, RMID0
    Core 19, L2ID 15, L3ID 1 => COS0, RMID0
    Core 21, L2ID 9, L3ID 1 => COS0, RMID0
    Core 23, L2ID 14, L3ID 1 => COS0, RMID0
    Core 25, L2ID 10, L3ID 1 => COS0, RMID0
    Core 27, L2ID 13, L3ID 1 => COS0, RMID0
    Core 29, L2ID 11, L3ID 1 => COS0, RMID0
    Core 31, L2ID 12, L3ID 1 => COS0, RMID0

Regards,
Zhuhe Fang

**Comment by mdcornu** [comment]
Hi Zhuhe,

Thanks for the quick response. 
It looks like some monitoring events are failing to start.

Can you please apply the following patch and upload the debug output:
[issue73_debug.zip](https://github.com/intel/intel-cmt-cat/files/2163213/issue73_debug.zip)

Run the following commands:
```
$ unzip issue73_debug.zip
$ git apply issue73_debug.patch
$ make clean && make DEBUG=y
$ sudo LD_LIBRARY_PATH=./lib ./pqos/pqos -I -p -V
```

The output should look similar to this:

```
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Monitoring top-pids enabled
.
.
DEBUG: 
Selected events: 0xc00f
Started events: 0xf00f
.
.
```
This should highlight which event is failing to start.
Please upload the complete output including capability information.

Regards,
Marcel

**Comment by fzhedu** [comment]
Hi, Marcel,
The output is shown as follows.

`sudo LD_LIBRARY_PATH=./lib ./pqos/pqos -I -p -V`
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
Monitoring top-pids enabled
INFO: CACHE: type 1, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 2, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 2, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 16 way(s), 1024 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 3, max id sharing this cache 16 (4 bits)
DEBUG: CACHE: not inclusive, complex cache indexing, 11 way(s), 16384 set(s), line size 64, 1 partition(s)
DEBUG: Detected core 0, socket 0, L2 ID 0, L3 ID 0, APICID 0
DEBUG: Detected core 1, socket 1, L2 ID 8, L3 ID 1, APICID 16
DEBUG: Detected core 2, socket 0, L2 ID 7, L3 ID 0, APICID 14
DEBUG: Detected core 3, socket 1, L2 ID 15, L3 ID 1, APICID 30
DEBUG: Detected core 4, socket 0, L2 ID 1, L3 ID 0, APICID 2
DEBUG: Detected core 5, socket 1, L2 ID 9, L3 ID 1, APICID 18
DEBUG: Detected core 6, socket 0, L2 ID 6, L3 ID 0, APICID 12
DEBUG: Detected core 7, socket 1, L2 ID 14, L3 ID 1, APICID 28
DEBUG: Detected core 8, socket 0, L2 ID 2, L3 ID 0, APICID 4
DEBUG: Detected core 9, socket 1, L2 ID 10, L3 ID 1, APICID 20
DEBUG: Detected core 10, socket 0, L2 ID 5, L3 ID 0, APICID 10
DEBUG: Detected core 11, socket 1, L2 ID 13, L3 ID 1, APICID 26
DEBUG: Detected core 12, socket 0, L2 ID 3, L3 ID 0, APICID 6
DEBUG: Detected core 13, socket 1, L2 ID 11, L3 ID 1, APICID 22
DEBUG: Detected core 14, socket 0, L2 ID 4, L3 ID 0, APICID 8
DEBUG: Detected core 15, socket 1, L2 ID 12, L3 ID 1, APICID 24
DEBUG: Detected core 16, socket 0, L2 ID 0, L3 ID 0, APICID 1
DEBUG: Detected core 17, socket 1, L2 ID 8, L3 ID 1, APICID 17
DEBUG: Detected core 18, socket 0, L2 ID 7, L3 ID 0, APICID 15
DEBUG: Detected core 19, socket 1, L2 ID 15, L3 ID 1, APICID 31
DEBUG: Detected core 20, socket 0, L2 ID 1, L3 ID 0, APICID 3
DEBUG: Detected core 21, socket 1, L2 ID 9, L3 ID 1, APICID 19
DEBUG: Detected core 22, socket 0, L2 ID 6, L3 ID 0, APICID 13
DEBUG: Detected core 23, socket 1, L2 ID 14, L3 ID 1, APICID 29
DEBUG: Detected core 24, socket 0, L2 ID 2, L3 ID 0, APICID 5
DEBUG: Detected core 25, socket 1, L2 ID 10, L3 ID 1, APICID 21
DEBUG: Detected core 26, socket 0, L2 ID 5, L3 ID 0, APICID 11
DEBUG: Detected core 27, socket 1, L2 ID 13, L3 ID 1, APICID 27
DEBUG: Detected core 28, socket 0, L2 ID 3, L3 ID 0, APICID 7
DEBUG: Detected core 29, socket 1, L2 ID 11, L3 ID 1, APICID 23
DEBUG: Detected core 30, socket 0, L2 ID 4, L3 ID 0, APICID 9
DEBUG: Detected core 31, socket 1, L2 ID 12, L3 ID 1, APICID 25
DEBUG: Adding monitoring event: resource ID 1, type 1 to table index 0
DEBUG: Adding monitoring event: resource ID 1, type 4 to table index 1
DEBUG: Adding monitoring event: resource ID 1, type 2 to table index 2
DEBUG: Adding monitoring event: resource ID 1, type 8 to table index 3
DEBUG: Adding monitoring event: resource ID 0, type 32768 to table index 4
DEBUG: Adding monitoring event: resource ID 0, type 16384 to table index 5
INFO: Monitoring capability detected
INFO: CPUID.0x7.0: L3 CAT supported
INFO: L3 CDP is disabled
INFO: L3 CAT details: CDP support=1, CDP on=0, #COS=16, #ways=11, ways contention bit-mask 0x600
INFO: L3 CAT details: cache size 11534336 bytes, way size 1048576 bytes
INFO: L3CA capability detected
INFO: CPUID 0x10.0: L2 CAT not supported!
INFO: L2CA capability not detected
INFO: MBA details: #COS=8, linear, max=90, step=10
INFO: MBA capability detected
INFO: resctrl detected
INFO: OS support for CMT detected
INFO: OS support for L3 CAT detected
INFO: OS support for MBA detected
DEBUG: resctrl group COS1 detected
DEBUG: resctrl group COS2 detected
DEBUG: resctrl group COS3 detected
DEBUG: resctrl group COS4 detected
DEBUG: resctrl group COS5 detected
DEBUG: resctrl group COS6 detected
DEBUG: resctrl group COS7 detected
DEBUG: allocation init OK
DEBUG: Max RMID per monitoring cluster is 64
INFO: Perf monitoring not supported. Kernel version 4.6 or higher required.
INFO: Detected perf monitoring support for Retired CPU Instructions
INFO: Detected perf monitoring support for Unhalted CPU Cycles
DEBUG: monitoring init OK
ERROR: Failed to start all selected OS monitoring events
DEBUG: 
Selected events: 0xc00f
Started events: 0x0
pqos: monitor.c:835: monitor_setup: Assertion `ret == 0' failed.
Aborted


Regards,
Zhuhe Fang

**Comment by mdcornu** [comment]
Hi Zhuhe,

I am seeing more events being enumerated:
```
.
.
INFO: Perf monitoring not supported. Kernel version 4.6 or higher required.
INFO: Detected perf monitoring support for Retired CPU Instructions
INFO: Detected perf monitoring support for Unhalted CPU Cycles
INFO: Detected resctrl support for LLC Occupancy
INFO: Detected resctrl support Total Memory B/W
INFO: Detected resctrl support for Local Memory B/W
DEBUG: monitoring init OK
.
.
```
Can you run this command and see what monitoring events are supported:
```
$ cat /sys/fs/resctrl/info/L3_MON/mon_features
llc_occupancy
mbm_total_bytes
mbm_local_bytes
```

If these are not being listed, please verify your kernel command line options.
To enable all features on your system it should look like:
`rdt=cmt,mbmtotal,mbmlocal,l3cat,l3cdp,mba`

Regards,
Marcel

**Comment by fzhedu** [comment]
Hi, Marcel,

cat /sys/fs/resctrl/info/L3_MON/mon_features
cat: /sys/fs/resctrl/info/L3_MON/mon_features: No such file or directory

Regards,
Zhuhe Fang

**Comment by poopbear** [comment]
Dear Zhuhe,

Would you let me know if your issue is solved as soon as possible?
I guess I have exactly same issue with you.

Sincerely,
Kyuyeon

**Comment by mdcornu** [comment]
Hi Zhuhe,

Have you tried adding `rdt=cmt,mbmtotal,mbmlocal,l3cat,l3cdp,mba` to your kernel command line and rebooting the system?

You can check your current kernel CL options with:
`$ cat /proc/cmdline`

Regards,
Marcel

**Comment by fzhedu** [comment]
Hi, Marcel,

Thanks for your continuous replying.

After adding the` rdt=cmt,mbmtotal,mbmlocal,l3cat,l3cdp,mba` to my kernel command line and rebooting the system, this issue is solved.

 @poopbear , you can try the solution.

Regards,
Zhuhe Fang
