### ISSUE TITLE
Associating cores or sockets to a COS for MBA

### ISSUE THREAD

**Issue by meteorfox** [intel/intel-cmt-cat#75]
I'm trying to limit memory bandwidth for all cores (e.g. 30%, 50% of available mem bw).

As I understood from the wiki, to allocate say 30% of memory bandwidth for COS1, I'd need to do this with pqos:

```
$ pqos -e "mba:1=30"
```

Then I can confirm it has been set:
```
$ pqos -s

L3CA/MBA COS definitions for Socket 0:
    L3CA COS0 => MASK 0x7ff
    L3CA COS1 => MASK 0x7ff
    L3CA COS2 => MASK 0x7ff
  [...]
    L3CA COS14 => MASK 0x7ff
    L3CA COS15 => MASK 0x7ff
    MBA COS0 => 100% available
  [ MBA COS1 => 30% available ]
    MBA COS2 => 100% available
    MBA COS3 => 100% available
    MBA COS4 => 100% available
    MBA COS5 => 100% available
    MBA COS6 => 100% available
    MBA COS7 => 100% available
```

I tried both with and without associating llc and cores using `pqos -a "core:1=0-35"` and `pqos -a "llc:1=0-35"`.

But regardless, it doesn't seem to be throttling the memory bandwidth.

I'm using 18-core w/ SMT Skylake SP and 64GB RAM on Linux 4.11.

To generate/measure memory bandwith I'm using Intel MLC v3.5 as follows, and with/without MBA I get the same numbers.

```
$ mlc --max_bandwidth -b669660 -t5

Using buffer size of 669.660MB/thread for reads and an additional 669.660MB/thread for writes

Measuring Maximum Memory Bandwidths for the system
Will take several minutes to complete as multiple injection rates will be tried to get the best bandwidth
Bandwidths are in MB/sec (1 MB/sec = 1,000,000 Bytes/sec)
Using all the threads from each core if Hyper-threading is enabled
Using traffic with the following read-write ratios
ALL Reads        :      63951.69
3:1 Reads-Writes :      63696.94
2:1 Reads-Writes :      62967.33
1:1 Reads-Writes :      59124.31
Stream-triad like:      63286.67
```

Any ideas what I could be missing?

**Comment by mdcornu** [comment]
Hi Carlos,

Thanks for contacting us.
You are throttling cores correctly.

I have re-run your benchmark and I see the same result. 
One possible reason for this is that there is not enough B/W being generated by individual cores.

When MBA is used to restrict memory B/W for a core, it restricts relative to the theoretic max B/W that can be generated by the core. 

For example, if a single core can generate up to 20GB/s of memory B/W and MBA is used to throttle the core by 50%, the core is now restricted to ~10GB/s B/W.
However, if the application running on that core is only generating 3GB/s then this restriction will have no effect as there is still ~7GB/s B/W available to the core.

In your case, because all cores are being utilized to saturate the memory sub-system, each individual core is not generating enough B/W to see the effect of the restriction.

I ran a similar test but with larger buffer size and restricted the test to a single core and I see the restriction take effect:
```
BEFORE RESTRICTION:
Command line parameters: --max_bandwidth -b9000000 -t5 -m0x1

Using buffer size of 9000.000MB/thread for reads and an additional 9000.000MB/thread for writes

Measuring Maximum Memory Bandwidths for the system
Will take several minutes to complete as multiple injection rates will be tried to get the best bandwidth
Bandwidths are in MB/sec (1 MB/sec = 1,000,000 Bytes/sec)
Using all the threads from each core if Hyper-threading is enabled
Using traffic with the following read-write ratios
ALL Reads        :      11520.02
3:1 Reads-Writes :      15424.44
2:1 Reads-Writes :      16443.49
1:1 Reads-Writes :      19233.54
Stream-triad like:      11555.99

AFTER RESTRICTION:
ALL Reads        :      2294.98
3:1 Reads-Writes :      3061.18
2:1 Reads-Writes :      3441.89
1:1 Reads-Writes :      4591.03
Stream-triad like:      2749.13
```
This is because the single core can generate higher B/W making the restriction more effective.

Regards,
Marcel

**Comment by meteorfox** [comment]
@mdcornu Thanks for the explanation. I see, that make sense.

I'm able to reproduce your test restricted to a single core as well, and see a similar result to what you showed.

**Comment by SirAbedi** [comment]
Hello Marcel,

I have a quick question about your comment, when you said that MBA "restricts relative to the theoretic max B/W that can be generated by the core".
What does theoretic max B/W means? How is it calculated?

If I want to add a constraint on a core, say 5 GB/s, I need to know the maximum B/W, so I can decide to choose 10%, 20%, or something else.

Also, I'm curious how MBA technology works? I've read in Intel Software Developer's manual that "Programmable Request Rate Controller" on each core implements MBA feature, but it doesn't say how the controller enforce memory B/W constraint. Does it count the number of cache misses in L2? Does it periodically check the B/W utilization of the core and throttles it? If yes, what is the granularity of this period, 1 us, 1 ms, or 1 second?

Thank you,
Saeed

**Comment by mdcornu** [comment]
Hi Saeed,

Unfortunately it is very difficult to calculate the max B/W that can be generated by the core as this varies widely depending on platform, system configuration, application memory operation types (e.g. reads/writes) etc. 
Right now, the best way for you to find the correct constraint (e.g. ~5GB/s) is to manually restrict B/W using MBA to find the correct percentage. 

A tool like Intel® Memory Latency Checker (MLC), mentioned above is a good option to stress the core and report max memory B/W generated with different memory operation types.
Example command would be: `sudo ./mlc --max_bandwidth -m0x4`

There is a new feature under development in the Linux kernel to allow specifying a MBA constraint in MB/s. For more information, please see the link below:
https://lkml.org/lkml/2018/4/20/919

For MBA technology, the Software Developers Manual contains all of the publicly available implementation details.

Regards,
Marcel
