### ISSUE TITLE
mba cannot limit memory bandwidth in centos7

### ISSUE THREAD

**Issue by ufo19890607** [intel/intel-cmt-cat#76]
Hi
I want to test the mba feature using the pqos library.  I followed the Usage Example for Memory Bandwidth Allocation (MBA) usage and tried to set COS 1 to 50% available. 
     #pqos -e "mba:1=50"
    SOCKET 0 MBA COS1 => 50% requested, 50% applied
    SOCKET 1 MBA COS1 => 50% requested, 50% applied
    Allocation configuration altered.

Then I tried to associate COS 1 with all cores in my server. I invoked pqos_alloc_assoc_set funcs
  ...
    for (i=0; i < total_cores; i++) {
              ret = pqos_alloc_assoc_set(i, clos1);
    }

After that I ran the stream benchmark but found the result was as same as not limiting the memory bandwitdh with mba.  Below is the two results of stream.
1. limit memory bandwidth
STREAM version $Revision: 5.10 $
This system uses 8 bytes per array element.
Array size = 5000000000 (elements), Offset = 0 (elements)
Memory per array = 38147.0 MiB (= 37.3 GiB).
Total memory required = 114440.9 MiB (= 111.8 GiB).
Each kernel will be executed 10 times.
 The *best* time for each kernel (excluding the first iteration)
 will be used to compute the reported bandwidth.
Number of Threads requested = 62
Number of Threads counted = 62
Your clock granularity/precision appears to be 1 microseconds.
Each test below will take on the order of 574852 microseconds.
   (= 574852 clock ticks)
Increase the size of the arrays if this shows that
you are not getting at least 20 clock ticks per test.
Function    Best Rate MB/s  Avg time     Min time     Max time
Copy:          120854.3     0.688862     0.661954     0.735460
Scale:         120879.7     0.695683     0.661815     0.764454
Add:           135193.4     0.917135     0.887617     0.951143
Triad:         132644.6     0.938034     0.904673     1.006038

2. unthrottle memory bandwidth
Function    Best Rate MB/s  Avg time     Min time     Max time
Copy:          123697.9     0.654386     0.646737     0.675376
Scale:         124752.0     0.648351     0.641272     0.663941
Add:           138963.0     0.873816     0.863539     0.889027
Triad:         139034.5     0.893346     0.863095     0.977505

[root@spdk-213 stream]# lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
Stepping:              4
CPU MHz:               1000.042
CPU max MHz:           3700.0000
CPU min MHz:           1000.0000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              22528K
NUMA node0 CPU(s):     0-15,32-47
NUMA node1 CPU(s):     16-31,48-63

OS: centos7.3  Kernel version: 3.10.0-514.16.1.el7.x86_64

**Comment by mdcornu** [comment]
Hi, 

Can you please read the response to issue #75.
This similar issue gives a brief explanation of one potential reason for not seeing the expected reduction in memory B/W.

A simple way to check this is to re-run your test with COS1 set to 10% (minimum) and see if you see reduced B/W. If so, it is likely that stream just isn't generating enough B/W for 50% to have an effect.

Regards,
Marcel

**Comment by mdcornu** [comment]
I hope my response was helpful. Closing this issue for now.
Feel free to re-open if needed.

Regards,
Marcel
