### ISSUE TITLE
Minor issue with man page

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-cmt-cat#79]
The manual has an issue in line 89 as detected by Debian's QA process:

/usr/share/man/man8/pqos.8.gz 89: warning [p 2, 2.3i]: cannot adjust line

see: https://lintian.debian.org/tags/manpage-has-errors-from-man.html

To show the error use:

LC_ALL=en_US.UTF-8 MANROFFSEQ='' MANWIDTH=80 man --warnings -E UTF-8 -l -Tutf8 -Z pqos/pqos.8 >/dev/null

<standard input>:89: warning [p 2, 2.3i]: cannot adjust line
<standard input>:89: warning [p 2, 2.5i]: can't break line

**Comment by mdcornu** [comment]
Man page updated to fix style issue, closing issue.
Feel free to reopen is necessary.

Regards,
Marcel
