### ISSUE TITLE
LLC monitoring output looks insane on Broadwell machine

### ISSUE THREAD

**Issue by renzhengeek** [intel/intel-cmt-cat#81]
Hello,

Thanks for creating this tool set! It's great for play the RDT thingy. But, I'm facing a weird problem as below:

On Broadwell machine(Intel(R) Xeon(R) CPU E5-2682 v4) with 3.10 kernel, I did:

1. On terminal1

```
$sudo pqos -m "llc:63"
TIME 2018-07-17 14:53:25
    CORE   IPC   MISSES    LLC[KB]
      63  0.00      26k        0.0
```

2. On termintal2:
```
$sudo taskset -ca 63 ./load_L3
```

**load_L3** just does sequential read in a loop within a memory set (6M).

The problem is that LLC value on Terminal1 always starts with random value (from hundreds to thousands ), and then drops down  until **0**, while load_L3 is still running.

And when I ctr+c, it shows the following warning:

```
WARN: Core 63 RMID association changed from 127 to 0! The core has been hijacked!
```

But, I also tried on Skylake machine, and the testing results are expected, and without that warning.

Hope for any insights on this problem :-)

**Comment by renzhengeek** [comment]
More informations:

- CPU info

```
$lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
Stepping:              1
CPU MHz:               1199.902
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4988.40
Virtualization:        VT-x
Hypervisor vendor:     vertical
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              40960K
NUMA node0 CPU(s):     0-63
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb invpcid_single pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local cat_l3
```

- pqos -s

I only did CMT, no CAT and MBA.

```
$sudo pqos -s                                                                                                                                       [62/1968]
NOTE:  Mixed use of MSR and kernel interfaces to manage                                                                                                      
       CAT or CMT & MBM may lead to unexpected behavior.
L3CA COS definitions for Socket 0:         
    L3CA COS0 => MASK 0xfffff              
    L3CA COS1 => MASK 0xfffff              
    L3CA COS2 => MASK 0xfffff              
    L3CA COS3 => MASK 0xfffff              
    L3CA COS4 => MASK 0xfffff              
    L3CA COS5 => MASK 0xfffff              
    L3CA COS6 => MASK 0xfffff              
    L3CA COS7 => MASK 0xfffff              
    L3CA COS8 => MASK 0xfffff              
    L3CA COS9 => MASK 0xfffff              
    L3CA COS10 => MASK 0xfffff             
    L3CA COS11 => MASK 0xfffff             
    L3CA COS12 => MASK 0xfffff             
    L3CA COS13 => MASK 0xfffff             
    L3CA COS14 => MASK 0xfffff             
    L3CA COS15 => MASK 0xfffff            
L3CA COS definitions for Socket 1:                           
    L3CA COS0 => MASK 0xfffff             
    L3CA COS1 => MASK 0xfffff
    L3CA COS2 => MASK 0xfffff
    L3CA COS3 => MASK 0xfffff
    L3CA COS4 => MASK 0xfffff
    L3CA COS5 => MASK 0xfffff
    L3CA COS6 => MASK 0xfffff
    L3CA COS7 => MASK 0xfffff
    L3CA COS8 => MASK 0xfffff
    L3CA COS9 => MASK 0xfffff
    L3CA COS10 => MASK 0xfffff
    L3CA COS11 => MASK 0xfffff
    L3CA COS12 => MASK 0xfffff
    L3CA COS13 => MASK 0xfffff
    L3CA COS14 => MASK 0xfffff
    L3CA COS15 => MASK 0xfffff
```

**Comment by mdcornu** [comment]
Hi Eric,

From the flags in your cpuinfo output, I can see you have OS support for some RDT features.
`cqm rdt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local cat_l3`

As stated in the pqos output `Mixed use of MSR and kernel interfaces to manage CAT or CMT & MBM may lead to unexpected behavior.` 
Although it is not obvious when this is occurring, I believe the OS is overwriting your configuration.

Please make sure the Resctrl filesystem is not mounted with:
`$ sudo umount resctrl`
For more information on Resctrl, please see our [wiki](https://github.com/intel/intel-cmt-cat/wiki/resctrl).

Also, please ensure no other applications on the system are monitoring with the Linux _perf_ tool as if RDT monitoring is enabled through perf, this will also overwrite your configuration.

If the problem is still occurring after these steps, please post the output of the commands:
`$ sudo pqos -I -V -s` and `$ sudo pqos -I -V -D`

Regards,
Marcel

**Comment by renzhengeek** [comment]
>Also, please ensure no other applications on the system are monitoring with the Linux perf tool as if RDT monitoring is enabled through perf, this will also overwrite your configuration.

Hi! You're right! There is perf-monitoring tool running background on my system. **pqos** works fine after stopping the monitoring daemon.

Thanks a lot. You save much of my time 👍
