### ISSUE TITLE
[Question] Is CAT (or pqos) work conserving?

### ISSUE THREAD

**Issue by poopbear** [intel/intel-cmt-cat#83]
Hi,

I have a question about feature of CAT.

I am using **Intel Xeon Silver 4110 CPU**, which has total **11 cache ways (11 MB of LLC)** and **16 cores** (8 cores with hyper-threading). In addition, I am using only **OS interface** on this pqos application.

- **Core 0-7** were associated to **COS 1**, which was modified to use **10 cache ways** (0x7fe).
```
pqos -I -e "llc:1=0x7fe;"
pqos -I -a "llc:1=0-7;"
```
- **Core 8-15** were associated to **COS 2**, which was modified to use **1 cache way** (0x001).
```
pqos -I -e "llc:2=0x001;"
pqos -I -a "llc:2=8-15;"
```

From now, with ***taskset*** utility, **Benchmark A** starts to run on **core 0-7**, on the otherhand, **Benchmark B** starts to run on **core 8-15**. In this situation, are **core 0-7** always limited to use only about **10 MB (10 ways)** of LLC? Similarly, are **core 8-15** limited to use only about **1 MB (1 way)** of LLC?

Actually, using CMT to monitor LLC for each group with `pqos -I -m "all:[0-7],[8-15];"`, I usually saw that **core 8-15**, which are associated to **COS 2**, use **more than 1 MB** of LLC total.

As a result, I guess if CAT (or pqos) has ***work conserving*** feature. In other words, does CAT guarantee only minimal bandwidth of LLC ways? Does each core try to use LLC as much as possible?

I am worried about my question being quite confusing, please leave me a comment if you need more explanation.

**Comment by mdcornu** [comment]
Hi Kyuyeon,

As mentioned in our [README](https://github.com/intel/intel-cmt-cat/blob/33a583d85076f488d528cc4b906e8eece4e370b3/README#L159), please find errata for Intel(R) Xeon(R) Processor Scalable Family [here](https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/xeon-scalable-spec-update.pdf?asset=14615).

I believe errata 17 and 18 outlined in the document above may help understand why you might see more LLC occupancy reported than allocated on this CPU.

Regards,
Marcel

**Comment by poopbear** [comment]
Thank you very much for your help.

**Comment by cliffburdick** [comment]
@mdcornu sorry to bring up an old issue, but do you know what the errata means by "under certain conditions"? It seems the test above was fairly simple, and it occurred. Is there a more detailed explanation of what doesn't work on scalable processors?

**Comment by poopbear** [comment]
@cliffburdick 
Hello, I solved this problem by giving cores to COS, concerning the L2ID that each core has.

In Xeon Scalable Processor Silver, 
Core 0-3: L2ID 0
Core 4-7: L2ID 1
Core 8-11: L2ID 0
Core 12-15: L2ID 1

Before, I give core 0-7 to COS 1 and 8-15 to COS 2, (see the test above)
so L2ID was mixed in single COS.
Cores in COS 1 use different L2ID at the same time, so the COS 2.

I solved this problem by giving core 0-3 and 8-11 to COS 1,
and core 4-7 and 12-15 to COS 2, to make each COS using same L2 IDed cache.

I definitely could see each COS use exact amount of LLC I wanted,
even 10MB and 1MB. I gave consistent result.

I hope this answer might be help.

**Comment by tkanteck** [comment]
Hello @cliffburdick,

I am not aware of any other documentation apart from already mentioned errata.
I don't think that L2ID has any impact on managing LLC. Did you mean L3ID instead of L2ID? Which CPU model do you use?

Thanks,
Tomasz

**Comment by cliffburdick** [comment]
Thanks @poopbear  and @tkanteck. Yes, I was @poopbear meant L3ID since L2 is only mapped between two hyperthreaded cores. Does that sound like what you think?

**Comment by tkanteck** [comment]
Thanks @cliffburdick and sorry for not tagging my reply correctly.

@poopbear 
Different L3ID values would mean different CPU sockets. Then each CPU socket has its own instance of L3/LLC which can be managed separately.

@poopbear and @cliffburdick 
Which CPU model do you use? It Intel(R) Xeon(R) SP Sky Lake or Cascade Lake generation?
Two comments here:
- As far as I remember there is errata for CMT for Sky lake generation, so it may not be 100% accurate
- Despite CMT reporting more than configured through CAT, resource allocation takes place and workloads can benefit from this technology

**Comment by cliffburdick** [comment]
Hi @tkanteck , we are using the SkyLake SP series. Did Cascade lake fix something?

**Comment by poopbear** [comment]
Hi @tkanteck, thanks for you comments, we had used Xeon Scalable Silver 4110, which is also Sky Lake generation.

**Comment by tkanteck** [comment]
Please have a look into this publication. You may find it useful.
https://software.intel.com/en-us/intel-resource-director-technology-rdt-reference-manual
