### ISSUE TITLE
Netdata plugin for graphing pqos

### ISSUE THREAD

**Issue by vsarunas** [intel/intel-cmt-cat#84]
Hi,

It would be very nice to see CMT stats graphed as a Netdata plugin, for example here is some example system: https://frankfurt.my-netdata.io/default.html#menu_cpu_submenu_utilization;theme=slate;help=true

If running on a physical system, netdata already has plugins which graph CPU throttling and CPU frequency in addition to the more common monitoring.

Sarunas

**Comment by tkanteck** [comment]
Hi Sarunas,
At the same time, feel to free to contribute to the project and implement the plugin yourself.
We'll be happy to help you if you have any questions.
Thanks,
Tomasz

**Comment by mdcornu** [comment]
Closing this issue for now. As mentioned above, will look into this if possible or are happy to accept pull requests from the community.

Thanks again for the  suggestion.

Regards,
Marcel
