### ISSUE TITLE
tid or pid for L3 CAT?

### ISSUE THREAD

**Issue by ccrhx4** [intel/intel-cmt-cat#85]
Hello,

I am using PQOS command line tool to set the L3 cache ways for apps running in the docker container.

My steps are:
1. sudo pqos -I -e "llc:1=0xf"
2. sudo pqos -I -a "pid:1=24554" 24554 is the PID of a process running.

I have checked the setting, the all the threads id of PID 24554 is not automatically set to COS 1.

Do I need to put all the tids of one process when setting the L3CAT? 

Thanks.

Hx

**Comment by mdcornu** [comment]
Hi Hx,

For TID/PID allocation, the libpqos library is using the [Resctrl](https://kernel.googlesource.com/pub/scm/linux/kernel/git/tip/tip/+/x86/cache/Documentation/x86/intel_rdt_ui.txt) Linux interface.

I believe this works on a task (TID) basis and the rule is any **new** tasks created will be added to their parents resctrl group (COS). In your case, your tasks already exist in the default COS group so the command above will only move the specified TID and all other tasks will remain in their existing COS group.

In this case, using the pqos tool, you will have to associate all process tasks the the COS.

Another possible option would be to use the [rdtset](https://github.com/intel/intel-cmt-cat/tree/master/rdtset) tool.
This will allow you to start a new application and do COS definition and association of all application tasks in a single command.
E.g. `rdtset -I -t 'l3=0xf' <application to run>`

Regards,
Marcel

**Comment by ccrhx4** [comment]
Hi Marcel,
Thank you for the clarification. And rdtset is a good idea for me.

Hx
