### ISSUE TITLE
Can we run CAT and CMT in parallel ?

### ISSUE THREAD

**Issue by ccrhx4** [intel/intel-cmt-cat#86]
Hello again,

I am trying to do the CMT and CAT in two processes to control and monitor the llc occupancy. I did the follow experiment and found my CAT setting was erased.

1. Use "sudo pqos -I -a "pid:1=23613" to set PID 23613 to COS1.
2. Start one child process of 23613.
3. Check by "sudo pqos -I -s", all the child process/threads are in COS1.
4. While the child process/threads are running, use "sudo pqos -I -p all:23613" to monitor the llc occupancy and then exit.
5. When all the child process/threads are finished, execute "sudo pqos -I -s" to check my setting.
23613 is back to COS0! 
But 23613 is still running.

Two findings:
1. if the pqos monitoring process does not exit, 23613 will stay in COS1.
2. if never start to monitor 23613, 23613 is fine in COS1 when threads exit.

Testing Env:
CPU Model: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
OS Version: CentOS 7.5
Kernerl Version: 3.10.0-862.9.1.el7.x86_64

Any idea? Really appreciated.

Hx

**Comment by kmabbasi** [comment]
Hi Hx,

Thanks for your feedback.
We spent some time investigating this issue and our observations lead us to believe that this is potentially a bug in the underlying resctrl kernel framework. We are going to report this issue to the responsible developers and keep this thread open until we determine a cause for this behavior.

Thanks,
Khawar

**Comment by kmabbasi** [comment]
Hi Huanxing,

Thanks for investigating this issue. Glad to hear that you found workaround and CAT works for you.
I am going to close this issue for now. Feel free to reopen in future if needed.

Thanks,
Khawar
