### ISSUE TITLE
OS interface

### ISSUE THREAD

**Issue by czafra** [intel/intel-cmt-cat#87]
Hi,

Do you have any plans to make the library functional without the need of reading MSRs? Currently, even if you configure pqos to only use the OS interface, the code tries to access MSR to figure out whether CDP is available. Getting rid of the MSRs and relying exclusively on restctrl will allow everybody to run code without special permissions.

Regards,

Carlos

**Comment by mdcornu** [comment]
Hi Carlos,

You are correct, removing the dependency on the MSR driver when using the OS interface is something we plan to do. However, as these tools are programming HW, they will always need to be run with root privileges whether you are using the MSR/OS interface.

If removing the MSR driver dependency is something you require soon, feel free to submit a pull request. We are always happy to receive contributions.

Regards,
Marcel

**Comment by czafra** [comment]
Hi Marcel,

Thank you for your answer.

It is true that mounting resctrl will require root access although this can be solved at boot time. Once resctrl is mounted and the right permissions have been applied, there absolutely no need to have root access.  

I will see if I get some time to try to make pqos MSR free.

Regards,

Carlos
