### ISSUE TITLE
Error with 1 vCPU

### ISSUE THREAD

**Issue by csoma** [intel/intel-cmt-cat#92]
https://github.com/intel/intel-cmt-cat/blob/master/lib/machine.c#L67

The `machine_init(const unsigned max_core_id)` function has a 
   `if (max_core_id == 0) return MACHINE_RETVAL_PARAM; `
line, which errors out on machines with 1 virtual cpu (one core, one thread).

If I comment out this line, pqos works.

To reproduce:

```bash
$ edit /etc/default/grub
GRUB_CMDLINE_LINUX=" nr_cpus=1 rdt=cmt,mbmtotal,mbmlocal,l3cat,l3cdp,l2cat,l2cdp,mba "
$ update-grub
$ reboot

$ pqos -s
ERROR: machine_init() error 2
Error initializing PQoS library!
```

**Comment by mdcornu** [comment]
Hi Csaba,

You are correct, this is an issue.
Expect a patch to correct this soon and thanks for highlighting.

Just out of curiosity, are you using the tool from within a guest VM or on a host machine?
We are always interested in hearing about how these tools are used so any information is greatly appreciated.

Regards,
Marcel

**Comment by mdcornu** [comment]
Closing issue as [fix ](https://github.com/intel/intel-cmt-cat/commit/61a8cc2e78d84df832dbd74a442ab55044326141) has been merged.

Feel free to reopen if needed.

Regards,
Marcel
