### ISSUE TITLE
Question about pqos output

### ISSUE THREAD

**Issue by abadouu** [intel/intel-cmt-cat#97]
Hi,

I would like to ask if is there a way to modify properly, so I can get instructions and cycles instead of getting IPC as output for every time interval?

Thanks

**Comment by dgiantsidi** [comment]
Hi!

All measurements are stored in `struct pqos_event_values` (periodically in monitor.c). 
Thus, you can do (add this lines in monitor_loop() in monitor.c:
```
mon_number = get_mon_arrays(&mon_grps, &mon_data);
// take the measurement
memcpy(mon_data, mon_grps, mon_number * sizeof(mon_grps[0]));
for (int i=0; i<mon_number;i++) {
    const struct pqos_event_values *ptr = &mon_data[i]->values;
    total_cycles = (long unsigned) ptr->ipc_unhalted;
    total_instructions = (uint64_t) ptr->ipc_retired;
}
```

Regards,
Dimitra

**Comment by kmabbasi** [comment]
Hi Abadouu,

Thanks to Dimitra for providing the solution. I am going to close this issue now.

Regards,
Khawar
